- docs/Using Randomness/vrf-contracts.md
> BSC addresses for Chainlink VRF

- _includes/_search.html
Fixes a bug where the last character you type isn't used for searching.
> change search events from keydown to keyup

- README.md
- package.json
- yarn.lock
This also slightly tweaks the readme.
> require version of yarn, clean up package.json

- docs/Additional Information/faq.md
A common question on the discord.
> Updated FAQ with Announcements Q&A

- docs/Data Provider Nodes/sport-monks-oracle.md
> Rectify typo in SportMonks Documentation

- docs/Additional Information/example-projects.md
Updated to markdown links and added hackathon tutorials
> Updated to markdown links and added hackathon tutorials

- docs/Using Randomness/get-a-random-number.md
> Add configuration values for vrf

- firebase.json
Added redirect for "/docs/getting-started"
> fix inbound link 2

- _data/navigation.js
- docs/Using Randomness/chainlink-vrf-api-reference.md
- docs/Using Randomness/get-a-random-number.md
- docs/Using Randomness/vrf-security-considerations.md
Co-authored-by: kaleofduty <59616916+kaleofduty@users.noreply.github.com>
Co-authored-by: Stephen Fluin <stephen.fluin@gmail.com>
> Add security warnings to VRF docs

- _data/navigation.js
- _tools/networks.ts
- docs/Developer Reference/link-token-contracts.md
- docs/Using Price Feeds/fantom-price-feeds.md
> add fantom price feeds

- docs/Using Price Feeds/reference-contracts.md
> add fantom and arbitrum to supported networks

- _tools/networks.ts
- docs/Developer Reference/link-token-contracts.md
> update fantom and avax explorer links

- _data/navigation.js
> fix data providers sidebar glitch

- docs/Keepers/compatible-contracts.md
- docs/Keepers/faqs.md
- docs/Keepers/introduction.md
This PR intentionally does not improve everything, this is a small first step. Additional updates will come as separate PR so they can be evaluated independently.
> update keepers with new explanations

- _tools/networks.ts
> add mainnet avalanche price feeds

- firebase.json
> add redirect for keepers bet page

- _tools/networks.ts
> move mainnet avax feeds above testnet

- docs/Introduction/tutorials/advanced-tutorial.md
- docs/Introduction/tutorials/beginners-tutorial.md
- docs/Introduction/tutorials/intermediates-tutorial.md
- docs/Node Operators/fulfilling-requests.md
- docs/Using Any API/make-a-http-get-request.md
- docs/Using Price Feeds/get-the-latest-price.html
- docs/Using Price Feeds/historical-price-data.html
- docs/Using Randomness/get-a-random-number.md
> updated gists and fixed path to contracts repo

- docs/External Initiators/building-external-initiators.md
> remove youtube reverence for external initiators

- docs/Developer Reference/link-token-contracts.md
> add avax mainnet contract

- firebase.json
> create redirect for example-walkthrough

- docs/Using Price Feeds/feed-registry.html
This PR applies some small improvements to the phrasing of the intro section of the feed registry docs.
> Improve phrasing in feed registry docs

- docs/Developer Reference/link-token-contracts.md
> add heco to the list of supported chains

- docs/chainlink-keepers/register-upkeep.md
Providing more context for how to think about minimum balance.
> Chainlink Keepers - Update register-upkeep.md - adding section for Maintaining a minimum balance

- docs/chainlink-keepers/compatible-contracts.md
I was reading through this section and want to make sure no one misses the gas limits; previous iteration didn't feel like a strong enough call out.
> Keepers - Making gas limits more prominent

- _includes/samples/keeper/cannotExecute.sol
- _includes/samples/keeper/checkData.sol
- _includes/samples/keeper/configureCheckUpkeep.sol
- _includes/samples/keeper/example.sol
- _includes/samples/keeper/expensiveComputation.sol
- _includes/samples/keeper/performData.sol
- _includes/samples/keeper/validationOfTriggers1.sol
- _includes/samples/keeper/validationOfTriggers2.sol
> add keeper examples

- docs/Using Randomness/get-a-random-number.md
Providing more context around network congestion.
> VRF Get Randomness Update

- _data/navigation.js
- _tools/networks.ts
- docs/Using Price Feeds/harmony-price-feeds.md
> add harmony testnet feeds

- docs/Data Provider Nodes/data-provider-nodes.md
- docs/Data Provider Nodes/flightaware-chainlink-testnet.md
- firebase.json
Fixes issue https://github.com/smartcontractkit/documentation/issues/291
- Restore ./flightaware-chainlink-testnet/
- Add to the data providers list.
- Remove the redirect.
> Restore flightaware docs

- docs/Using Any API/make-a-http-get-request.md
Updated "Make a GET Request" code sample to point to the DevRel node and it's "Get > Uint256" job.
> Update Get Request with DevRel Node

- CODEOWNERS
> Add @dwightjl to codeowners

- docs/Introduction/tutorials/advanced-tutorial.md
Updated Advanced tutorial to point to DevRel node and JobId. Also changed some code to match "make a get request" code sample.
> Advanced Tutorial Node Update

- docs/Data Provider Nodes/data-provider-nodes.md
> add new data providers

- _includes/samples/APIRequests/ATestnetConsumer.sol
> update testnet consumer sample

- docs/Data Provider Nodes/chainlink-alarm-clock.md
- docs/Data Provider Nodes/dns-ownership-oracle.md
- docs/Data Provider Nodes/finage-global-market-data-oracle.md
- docs/Data Provider Nodes/google-weather.md
- docs/Data Provider Nodes/kraken-rates-oracle-node.md
- docs/Data Provider Nodes/lcx-testnet.md
- docs/Developer Reference/user-guides/deploy-your-first-contract.md
- docs/Introduction/tutorials/advanced-tutorial.md
- docs/Introduction/tutorials/beginners-tutorial.md
- docs/Introduction/tutorials/intermediates-tutorial.md
- docs/Node Operators/fulfilling-requests.md
- docs/Using Any API/existing-job-request.md
- docs/Using Any API/large-responses.md
- docs/Using Any API/make-a-http-get-request.md
- docs/Using Any API/multi-variable-responses.md
- docs/Using Price Feeds/feed-registry.html
- docs/Using Price Feeds/get-the-latest-price.html
- docs/Using Price Feeds/historical-price-data.html
- docs/Using Randomness/get-a-random-number.md
- docs/chainlink-keepers/compatible-contracts.md
Manually tested each link. It works!
> update code samples urls path

- _includes/samples/Keepers/KeepersCounter.sol
> remove unused interface from keeper code sample

- _tools/networks.ts
> update arbitrum mainnet explorer url

- docs/Developer Reference/link-token-contracts.md
> add optimism contracts to reference page

- docs/Using Randomness/vrf-best-practices.md
Looks like the same line is repeated across the 2nd and 3rd examples of handling multiple VRF requests in flight but is only relevant to the former
> Amend error in vrf-best-practices.md

- docs/Using Any API/contract-addresses.md
Removed POST job until the issue is worked out
> Update jobIds+oracle on "Contract Addresses" Page

- firebase.json
> redirect reference url

- docs/Node Operators/fulfilling-requests.md
> add node addresses terminology

- _tools/linkcheck.ts
- _tools/process-data.ts
- package.json
- tsconfig.json
- yarn.lock
Had to fix typescript errors, so I added a `tsconfig.json`.
> bump dependencies to latest versions

- _src/docs.css
> Fix element alignment on the docs homepage.

- docs/Node Operators/fulfilling-requests.md
View staged changes here: https://deploy-preview-208--dreamy-villani-0e9e5c.netlify.app/docs/fulfilling-requests
Changes for fulfilling-requests.md:
- Update the Gist link for ATestnetConsumer.sol. The previous Gist uses outdated import paths.
- Remove the callout for setting the Remix environment to Solidity. The language environment is set automatically when you open the Gist. **Environment** is a setting under **Deploy and Run**; not the Gists menu.
- Add alt text to images for accessibility.
- Clean up the requirements section to provide a full list of requirements rather that one requirement with many sub-requirements and one callout box.
- Convert some of the warnings into steps. Many of these warnings flow better as explicit steps in the process.
> Cleanup and simplify the "Fulfilling Requests" page.

- docs/Oracle Jobs/Job Types/direct_request.md
- docs/Oracle Jobs/migration-v1-v2.md
jobSpec.contractAddress doesn't exist for DR jobs, removing that from the migration docs
> Consistent DR specs

- chainlink-nodes.md
- contracts.md
- docs/Developer Reference/user-guides/use-your-first-contract.md
> remove chainlink explorer content

- docs/Developer Reference/link-token-contracts.md
This appears to be the correct address based on what I see here: https://github.com/smartcontractkit/gauntlet/blob/9e5fc66af17d54244d6aeea2e41e1ec8dea8c6af/networks/.env.avalanche-mainnet
> Update Avalanche Mainnet address

- _includes/nodes.liquid
> remove accidental borders

- firebase.json
> Add node operator overview redirect

- docs/Node Operators/configuration-variables.md
> Update ADMIN_CREDENTIALS_FILE default.

- docs/Developer Reference/link-token-contracts.md
- docs/Using Randomness/vrf-contracts.md
> Remove https://rinkeby-faucet.com/ links

- _data/navigation.js
- _src/docs.css
- docs/Introduction/tutorials/beginners-tutorial.md
- docs/chainlink-keepers/compatible-contracts.md
- docs/chainlink-keepers/register-upkeep.md
- docs/chainlink-keepers/utility-contracts.md
- focuses on ETH balance monitor Keeper-compatible utility contract
- outlines functions and their respective parameters
- Explains user only settings
> Add Keeper Utility Contract Page

- docs/Introduction/architecture-overview/architecture-decentralized-model.md
- docs/Using Price Feeds/historical-price-data.html
- Fixes #454 
- Adds specific link on historical price feeds page
- Adds TOC to Decentralized Data Model
- Adds more description in Aggregation Parameters section
> Add information about update parameters for price feeds

- docs/Node Operators/running-a-chainlink-node.md
> Update hw reqs

- docs/Introduction/tutorials/advanced-tutorial.md
- docs/Introduction/tutorials/intermediates-tutorial.md
- update TOC for both intermediate and advanced tutorial to only main headings
- update typo in intermediate tutorial
> Update TOC and typo intermediate/advanced tutorials

- _includes/samples/VRF/VRFExternalSubOwnerExample.sol
- docs/Using Randomness/get-a-random-number.md
Update the example code and documentation for the solidity changes
in https://github.com/smartcontractkit/chainlink/pull/5499
> update VRF external sub owner example

- docs/Introduction/getting-started.md
- docs/Oracle Jobs/migration-v1-v2.md
- docs/chainlink-keepers/introduction.md
- docs/chainlink-keepers/overview.html
- Started off with basic startup procedures
- Added section for beginner tutorials
- Dive deep section for each Chainlink product
- Added general resources at bottom
> Add landing page

- docs/Developer Reference/hackathon-resources.md
- added note on top of Hackathon Resources to route to Learning Resources
> Add routing from Hackathon Resources to Learning Resources

- docs/Oracle Jobs/Job Types/direct_request.md
I'm a total newbie, but the code made more sense with this change. If I'm wrong, sorry for wasting your time.
> change direct_request.md

- docs/Introduction/tutorials/intermediates-tutorial.md
> spelling correction

- _data/navigation.js
- _includes/samples/VRF/VRFSingleConsumerExample-simple.sol
- docs/Introduction/tutorials/advanced-tutorial.md
- docs/Introduction/tutorials/intermediates-tutorial.md
- docs/Using Randomness/chainlink-vrf.md
- docs/Using Randomness/example-contracts.md
- docs/Using Randomness/get-a-random-number.md
- docs/Using Randomness/v1/chainlink-vrf-api-reference.md
- docs/Using Randomness/v1/chainlink-vrf.md
- docs/Using Randomness/v1/get-a-random-number.md
- docs/Using Randomness/v1/vrf-best-practices.md
- docs/Using Randomness/v1/vrf-deployments.md
- docs/Using Randomness/v1/vrf-security-considerations.md
- docs/Using Randomness/vrf-best-practices.md
- docs/Using Randomness/vrf-deployments.md
- docs/Using Randomness/vrf-migration-v1-v2.md
- docs/Using Randomness/vrf-security-considerations.md
- firebase.json
Forked from https://github.com/smartcontractkit/documentation/pull/249 with multiple changes for GA.
> Add the VRF v2 launch documentation.

- docs/Developer Reference/fund-your-contract.md
> Fixed a typo on /fund-your-contract/

- docs/Oracle Jobs/Job Types/direct_request.md
fixed job spec and code example for single and multi word direct request jobs. 
Also added note about needing to use Operator.sol for multi-word or it won't work
> direct request multi word spec and contract fix

- docs/chainlink-keepers/register-upkeep.md
Ordering update, some simplification and adding note on block confirmation time.
> Updated Registration Completion section

- firebase.json
easier URL to hand out at live events
> add quick URL for newsletter sign-up

- _src/ens.js
- docs/Using Price Feeds/reference-contracts/ens.html
Update the ens page for better user experience for docs sprint
> docs: update ens page

- _includes/samples/Keepers/KeepersCounter.sol
- docs/chainlink-keepers/compatible-contracts.md
- docs/chainlink-keepers/introduction.md
- docs/chainlink-keepers/overview.html
- docs/chainlink-keepers/register-upkeep.md
- docs/chainlink-keepers/utility-contracts.md
- Consistent config formatting
- Incorrect parameters
- Reorganize some best practice information
- Update contracts to 0.8 where possible
> Fix several issues in the Keepers docs

- docs/Node Operators/run-an-ethereum-client.md
Recommended change from https://github.com/smartcontractkit/documentation/pull/511#issuecomment-1059737010
> Update API key paths for GetBlock connections

- _tools/networks.ts
- docs/Terra/DataFeeds/data-feeds-terra.md
Reverts smartcontractkit/documentation#655 to restore hard coded Terra feeds for now.
> Revert "Restore Terra testnet feed auto-processing"

- docs/Developer Reference/hackathon-resources.md
> Deleting extra ")" in hackathon resources page 

- docs/chainlink-keepers/introduction.md
> Keepers: Add Avalanche Fuji Testnet

- docs/Solana/DataFeeds/data-feeds-solana.md
- docs/Terra/DataFeeds/data-feeds-terra.md
- docs/Terra/DataFeeds/using-data-feeds-terra.md
- docs/Using Price Feeds/arbitrum-price-feeds.md
- docs/Using Price Feeds/avalanche-price-feeds.md
- docs/Using Price Feeds/data-feeds-moonriver.md
- docs/Using Price Feeds/fantom-price-feeds.md
- docs/Using Price Feeds/harmony-price-feeds.md
- docs/Using Price Feeds/optimism-price-feeds.md
Update terra testnet feeds for OCR2
> Update terra testnet feeds

- _includes/samples/VRF/VRFv2Consumer.sol
I don't think we actually need it. Let's find out!
> remove unneeded LINK address

- docs/Using Randomness/chainlink-vrf.md
Resolved issue where formula resolves to units of GWEI*LINK, resolved open `)` issue
> Fix subscription limit formula

- docs/Using Any API/request-and-receive-data.md
- docs/Using Price Feeds/get-the-latest-price.html
- docs/Using Randomness/chainlink-vrf.md
- docs/Using Randomness/get-a-random-number.md
- docs/chainlink-keepers/introduction.md
- add request warning to VRF steps 
- Fixes #710
> Add request warnings to VRF 

- docs/Oracle Jobs/Task Types/task_jsonparse.md
Documenting https://github.com/smartcontractkit/chainlink/pull/6408 and targeting 1.4
> task_jsonparse: add path separator

- docs/Using Randomness/get-a-random-number.md
- docs/chainlink-keepers/compatible-contracts.md
- docs/chainlink-keepers/overview.md
- docs/chainlink-keepers/util-overview.md
- update code formatted hyperlinks with (link) tag
Fixes #711
> Update code formatted hyperlinks

- _data/navigation.js
- _tools/process-data.ts
- docs/Solana/DataFeeds/using-data-feeds-off-chain.md
- docs/Solana/DataFeeds/using-data-feeds-solana.md
- docs/Solana/overview.md
Update the Solana documentation to use the new code samples
> Update the Solana documentation

- firebase.json
> add handy shortcut redirects

- docs/chainlink-keepers/supported-networks.html
- added Avalanche Fuji testnet to Keepers docs
- Fixes #752
> Add Avalanche Fuji Testnet to Keepers docs

- docs/Oracle Jobs/Job Types/direct_request.md
- docs/Oracle Jobs/Task Types/task_http.md
Added new HTTP task parameter and Direct Request new variables.
> Direct Request and HTTP task new parameters

- docs/Developer Reference/developer-communications.html
- docs/Introduction/architecture-overview.md
- docs/Introduction/architecture-overview/architecture-request-model.md
- docs/Node Operators/running-a-chainlink-node.md
- docs/Using Price Feeds/arbitrum-price-feeds.md
- docs/Using Price Feeds/avalanche-price-feeds.md
- docs/Using Price Feeds/bnb-chain-addresses.md
- docs/Using Price Feeds/data-feeds-gnosis-chain.md
- docs/Using Price Feeds/data-feeds-moonbeam.md
- docs/Using Price Feeds/data-feeds-moonriver.md
- docs/Using Price Feeds/ethereum-addresses.md
- docs/Using Price Feeds/fantom-price-feeds.md
- docs/Using Price Feeds/feed-registry.html
- docs/Using Price Feeds/get-the-latest-price.html
- docs/Using Price Feeds/harmony-price-feeds.md
- docs/Using Price Feeds/historical-price-data.html
- docs/Using Price Feeds/huobi-eco-chain-price-feeds.md
- docs/Using Price Feeds/matic-addresses.md
- docs/Using Price Feeds/optimism-price-feeds.md
- docs/Using Price Feeds/using-chainlink-reference-contracts.md
- docs/Using Randomness/chainlink-vrf.md
- docs/Using Randomness/example-contracts.md
- docs/Using Randomness/get-a-random-number.md
- docs/Using Randomness/v1/chainlink-vrf-api-reference.md
- docs/Using Randomness/v1/chainlink-vrf.md
- docs/Using Randomness/v1/get-a-random-number.md
- docs/Using Randomness/v1/vrf-best-practices.md
- docs/Using Randomness/v1/vrf-contracts.md
- docs/Using Randomness/vrf-best-practices.md
Removing the metadata image which is not compatible with Twitter.
```
image:
0: "/files/OpenGraph_V3.png"
```
> Fix documentation metadata

- docs/Introduction/architecture-overview/architecture-request-model.md
There doesn't seem to be an Oracle.sol file but the interface file could be helpful instead.
> Oracle contract link is broken

- docs/chainlink-keepers/supported-networks.html
- docs/home.html
- added info to Supported Networks page
> Add Keepers Avalanche config

- docs/chainlink-keepers/supported-networks.html
- update content to be aligned with VRF Contract Address page (../docs/vrf-contracts/)
- Update parts of docs to be in html
> Update Keeper's Supported Network Format

- _data/navigation.js
- _includes/samples/APIRequests/APIConsumer.sol
- _includes/samples/APIRequests/FetchFromArray.sol
- _includes/samples/APIRequests/GenericBigWord.sol
- _includes/samples/APIRequests/GetGasPrice.sol
- _includes/samples/APIRequests/MultiWordConsumer.sol
- docs/Introduction/tutorials/advanced-tutorial.md
- docs/Using Any API/array-response.md
- docs/Using Any API/contract-addresses.md
- docs/Using Any API/existing-job-request.md
- docs/Using Any API/large-responses.md
- docs/Using Any API/listing-services.md
- docs/Using Any API/make-a-http-get-request.md
- docs/Using Any API/multi-variable-responses.md
- docs/Using Any API/request-and-receive-data.md
- docs/Using Any API/single-word-response.md
- firebase.json
closes #814
Kovan is deprecated. Therefore , a Rinkeby Devrel node has been spun up and all the ANY API examples are updated to use Kovan instead of Rinkeby
- All ANY API examples
- Update DevRel nodes page  with list of jobs on Rinkeby
> ANY API: Kovan to Rinkeby

- docs/chainlink-keepers/job-scheduler.md
closes #825 
...
Need to add detail about gas used
...
- High level
- changes that
- you made
- ...
> Job Scheduler Gas fix - Closes #825

- docs/chainlink-keepers/util-overview.md
- docs/chainlink-keepers/utility-contracts.md
closes #836
...
Don't render backticks in title
- High level
- changes that
- you made
- ...
> improve EthBalanceMonitor formatting

- .github/workflows/chains-metadata.yml
Add permissions to `chains-metadata.yml` in order to be able to create branches and pull requests
permissions:
pull-requests: write
contents: write
> update permissions chains-metadata workflow

- docs/chainlink-keepers/keeper-economics.md
- docs/chainlink-keepers/supported-networks.html
Updated percentage premium (added %) to make it clear that this is a percentage that is added as requested by Sales
closes #850 
...
Made it clear that this adds a percentage to the cost and not some absolute amount
...
- High level
- changes that
- you made
- ...
> Updated percentage premium in Keepers

- docs/Oracle Jobs/Task Types/task_mode.md
closes #853
typos to be corrected in `task_mode.md`
Replaced _median_ by _mode_
> Correct mode task docs

- docs/chainlink-keepers/util-overview.md
- docs/chainlink-keepers/utility-contracts.md
- Add new Keepers example
- Change "Utility Contracts" to "Example Contracts"
> Add Keepers examples

- docs/Oracle Jobs/Job Types/cron.md
Add a note pointing out the Job Scheduler
> Add 'Job Scheduler' Note to cron page

- docs/Introduction/architecture-overview/off-chain-reporting.md
- Fixes formatting error on OCR page
> OCR Architecture Page Format 

- docs/chainlink-keepers/register-upkeep.md
- Update sender description for Keepers code sample
> Update sender description for Keepers code sample

- docs/Node Operators/running-a-chainlink-node.md
Clarify Ganache support for Chainlink Nodes
Closes #366
> Clarify the Ganache support statement

- docs/Additional Information/glossary.md
First pull request fixing minor grammatical issues.
> Editing to fix minor grammatical issues.

- firebase.json
> Redirect fix

- docs/chainlink-keepers/keeper-economics.md
- docs/chainlink-keepers/keepers-release-notes.md
min spend language improved to resolve #971
- High level
- changes that
- you made
- ...
> Updated language for Keepers minimum spend

- _includes/samples/NodeOperators/jobs/get-bytes32.toml
- _includes/samples/NodeOperators/jobs/get-string.toml
- _includes/samples/NodeOperators/jobs/get-uint256.toml
- docs/chainlink-nodes/job-specs/direct-request-get-bool.md
- docs/chainlink-nodes/job-specs/direct-request-get-bytes.md
- docs/chainlink-nodes/job-specs/direct-request-get-int256.md
- docs/chainlink-nodes/job-specs/direct-request-get-uint256.md
closes #995
Fix example Get > Uin256 job so that it can access external APIs
Added allowUnrestrictedNetworkAccess="true" to fetch task
> Fix fetch task in sample Get > Uint256 job to allow external access

- _includes/main.liquid
- Updates SmartCon banner for 09/26/2022
> Update SmartCon Banner

- docs/chainlink-keepers/job-scheduler.md
during Steph's polygon * chainlink talk at SmartCon I noticed no link to keepers app on this page specifically
...
created an issue, simple request to add a link to Keepers app on this page. 
https://github.com/smartcontractkit/documentation/issues/1005
...
- High level
- changes that
- you made
- ...
> add link to keepers app in this page

- docs/home.html
Add Arbitrum logo to Automation
...
- High level
- changes that
- you made
- ...
> Add Arbitrum logo to Automation

- firebase.json
> add vrf v2 redirect for /docs/vrf/v2/examples/get-a-random-number/

- docs/chainlink-automation/automation-economics.md
- provides clearer explanation of Automation pricing
> Update Automation Economics 

- src/config/site.ts
Fixes the baseUrl for the `Edit this page` link
> update config to fix dead links

- src/pages/vrf/v2/direct-funding/examples/get-a-random-number.md
> VRF v2: Callout directfunding remix gas limit setup

- .github/workflows/chainlink-automation-config.yml
[.github/workflows/chainlink-automation-config.yml](https://github.com/smartcontractkit/documentation/compare/aelmanaa/fix-cl-automation-config-workflow?expand=1#diff-9eb028c6667ef058425c27d65a345cfba963240a3926877bf8e27a5d184dfdd9) runs as a cron job on the main branch
> fix chainlink-automation-config worflow

- src/components/Header/Search/SearchModal.tsx
Adds classnames to links in the search modal to track clicks in google analytics
> Added classnames to searchmodal links for tracking

- src/pages/chainlink-nodes/running-a-chainlink-node.md
Not sure what EVN is, but I think it was meant to say EVM which is what is listed on the linked page.
...
...
- High level
- changes that
- you made
- ...
> Fixed typo

- src/pages/chainlink-automation/util-overview.md
- add Batch NFT
- add dNFT
- add VRF Subscription Monitor
> Update Automation Util Contracts

- src/config/sidebar.ts
- src/features/resources/callouts/ResourcesCallout.astro
- src/features/resources/callouts/read-bridge-risks.md
- src/pages/chainlink-automation/supported-networks.mdx
- src/pages/resources/bridge-risks.md
- src/pages/resources/link-token-contracts.md
- src/pages/vrf/v1/supported-networks.md
- src/pages/vrf/v2/direct-funding/supported-networks.md
- src/pages/vrf/v2/subscription/supported-networks.md
> Add cross-chain bridge risks

- src/pages/getting-started/other-tutorials.md
...
...
- High level
- changes that
- you made
- ...
> 🚀 Adding resources

- CODEOWNERS
Add thedriftofwords as a codeowner
> Add thedriftofwords as a codeowner

- public/samples/FeedRegistry/PriceConsumer.sol
- public/samples/PriceFeeds/HistoricalPriceConsumer.sol
- public/samples/PriceFeeds/NFTFloorPriceConsumerV3.sol
- public/samples/PriceFeeds/PriceConsumerV3.sol
- public/samples/PriceFeeds/PriceConsumerWithSequencerCheck.sol
- public/samples/PriceFeeds/ReserveConsumerV3.sol
closes #1112
...
Just a small improvement in the Solidity code example for Price Feeds. The comments are according to me better placed and more easy to read on multiple lines than on a single line. Things are explained in issue #1112.
...
- Code snippet improvement => more readable
> Updated Solidity Price Feeds example (PriceConsumerV3.sol)

- src/pages/chainlink-nodes/oracle-jobs/task-types/task_bridge.md
https://smartcontract-it.atlassian.net/browse/BCF-1966
Related to https://github.com/smartcontractkit/chainlink/pull/8293
> Added header docs to bridge task

- public/samples/APIRequests/APIConsumer.sol
- public/samples/APIRequests/ATestnetConsumer.sol
- public/samples/APIRequests/FetchFromArray.sol
- public/samples/APIRequests/GenericBigWord.sol
- public/samples/APIRequests/GetGasPrice.sol
- public/samples/APIRequests/MultiWordConsumer.sol
- src/pages/any-api/get-request/examples/array-response.md
- src/pages/any-api/get-request/examples/existing-job-request.md
- src/pages/any-api/get-request/examples/large-responses.md
- src/pages/any-api/get-request/examples/multi-variable-responses.md
- src/pages/any-api/get-request/examples/single-word-response.md
- src/pages/any-api/testnet-oracles.md
> any-api sepolia examples

- public/samples/VRF/VRFD20.sol
Fixes a code comment typo in VRFD20.sol.
> Typo fix in code comment

- src/pages/getting-started/intermediates-tutorial.md
**IMPORTANT: Please do not create a Pull Request without creating an issue first. Any change needs to be discussed before proceeding.**
closes #1154
**To Replicate the Issue:**
- Go to the the [getHouseName() function](https://docs.chain.link/getting-started/intermediates-tutorial#house-function) within the Getting Started -> Get Random Numbers - > "house function" section of the Chainlink docs.
- See the return houseNames[id.sub(1)]; at the bottom of the getHouseNames function.
- Compare the appearance of the line in the docs to the actual [VRFD20 contract](https://remix.ethereum.org/#url=https://docs.chain.link/samples/VRF/VRFD20.sol) (return houseNames[id - 1];)
- Replace this working line in the contract with the broken line from the docs (mentioned in step 2)
- Attempt to compile the …
> bugfix: "Get Random Numbers" Docs `getHouseName()` Fails to Compile and does not match VRFD20 Contract (ISSUE #1154)

- .eleventy/docs/chainlink-nodes/configuration-variables.md
- src/pages/chainlink-nodes/v1/configuration.md
Documenting core node env var changes from:
- https://github.com/smartcontractkit/chainlink/pull/7225
> chainlink-nodes: arbitrum gas estimator

- src/components/LeftSidebar/LeftSidebar.astro
- src/config/sidebar.ts
- src/layouts/MainLayout.astro
this breaks the active link on the sidebar, need to strip url params
there is no fallback shown
> poc for dynamic sidebar

- src/pages/architecture-overview/architecture-decentralized-model.md
- src/pages/architecture-overview/architecture-request-model.md
- src/pages/chainlink-automation/overview.md
- src/pages/data-feeds/feed-registry/index.mdx
- src/pages/data-feeds/historical-data.mdx
- src/pages/data-feeds/l2-sequencer-feeds.md
- src/pages/data-feeds/proof-of-reserve/index.md
- src/pages/vrf/v2/direct-funding/index.md
- src/pages/vrf/v2/subscription/index.md
Applies the `ClickToZoom` custom component to architecture diagrams that are difficult to view otherwise.
> Apply image zoom to architecture diagrams

- src/pages/chainlink-automation/job-scheduler.md
- closes #1192 
- Updates `cronUpkeepFactory` link
> Update Automation Cron Link

- scripts/reference/chains.json
- src/pages/resources/link-token-contracts.md
- src/scripts/reference/chains.json
- src/scripts/reference/linkNameSymbol.json
closes #1183 
...
the problem with the button for Arbitrum Goerli is that the id does not contain the Eth_chain_id so I have added that also the button does not work so I have added the JSON for the Arbitrum Goerli in the "src>pages>resources>scripts>reference>chains.json" as it was missing.
...
button for Arbitrum Goerli is not working, so I added the JSON for the Arbitrum Goerli in the chains.josn file. problem was on clicking the button "switch network and add to wallet" did not work for the same.
- High level
- changes that
- you made
- change the JSON file 
- ...
> Add to wallet btn for Arbitrum Goerli fixed #1183

- src/pages/data-feeds/ens.mdx
Closes #1199
On https://docs.chain.link/data-feeds/ens, _Naming Structure_ and _Subdomains_ paragraphs are duplicated.
Remove the duplicated sections: _Naming Structure_, _Subdomains_
> Remove duplicate paragraphs - issue #1199

- src/config/sidebar.ts
- places **Supported Networks** after **Introduction** on left nav
> Change location of Supported Networks on Automation side nav

- src/pages/chainlink-nodes/oracle-jobs/task-types/task_bridge.md
- src/pages/chainlink-nodes/v1/configuration.md
Remove optional `async` param and related reference in `BRIDGE_RESPONSE_URL`
> Remove async param

- src/pages/chainlink-nodes/v1/running-a-chainlink-node.md
...
...
- High level
- changes that
- you made
- ...
> using port 5432 instead of 5433 in secrets.toml

- src/pages/chainlink-nodes/v1/running-a-chainlink-node.md
closes #1253
Updating Goerli ChainID
Updated Goerli ChainID
> Goerli ChainID 5

- src/features/landing/data/index.ts
- src/pages/vrf/v2/direct-funding/index.mdx
- src/pages/vrf/v2/direct-funding/supported-networks.mdx
- src/pages/vrf/v2/subscription/index.mdx
- src/pages/vrf/v2/subscription/supported-networks.mdx
* Add minimum confirmations to direct funding networks page
* Sentence case for section headings
* Remove config info for Klaytn Baobob
* Remove Klatyn icons from docs homepage
> Misc VRF updates

- src/features/feeds/data/chains.ts
Preview: https://documentation-git-arb-polygon-nft-floor-chainlinklabs.vercel.app/data-feeds/nft-floor-price/addresses?network=polygon
> Add Polygon Mumbai to NFT Floor Price feeds

- public/samples/Automation/UpkeepIDConsumerExample.sol
- public/samples/Automation/UpkeepIDConsumerExamplev1.sol
- Ensure that solidity versions include `^` for programmatic upkeep
> Update solidity versions in contracts

- src/pages/chainlink-functions/resources/architecture.mdx
Updated 404 contract code links.
closes #1291 
...
Fixes Contract Code 404s on Functions Architecture Docs
...
Edited Contract Code links on Functions Architecture Docs to include live links.
> Fix Contract Code 404s on Functions Architecture Docs

- src/pages/chainlink-functions/tutorials/simple-computation.mdx
...
to address the issue raised by a hackathon participant here https://stackoverflow.com/questions/76231362/chainlink-functions-error-thrown-in-sandboxed-source-code-cannot-find-module
...
Add explanatory text to the source.js section of this doc
- ...
> Update info on JS source code constraints (no imports allowed)

- src/features/chainlink-functions/common/FunctionsConsumer.mdx
Links are broken in the current version.
> Fix broken links

- src/pages/chainlink-automation/overview.mdx
- fixes broken links on Automation homepage
- closes #1340
> Update Automation Links

- src/pages/chainlink-nodes/v1/secrets-config.mdx
Sync minor update from https://github.com/smartcontractkit/chainlink/pull/9691/ to update https://docs.chain.link/chainlink-nodes/v1/secrets-config#url-1
> Update secrets config - URL

- src/pages/vrf/v2/estimating-costs.mdx
Update repo link, fill in additional context.
Merge https://github.com/smartcontractkit/smart-contract-examples/pull/26 first
> Switch repo links for VRF/Arb code sample

- src/pages/chainlink-nodes/v1/running-a-chainlink-node.mdx
...
Small verbiage change to add clarity and aid in translations.
Add more clear verbiage on command use when running a node.
> Update running-a-chainlink-node for clarity

- src/components/HeadCommon.astro
...
...
- High level
- changes that
- you made
- ...
> Remove unnecessary weglot subdomains

- src/pages/data-feeds/historical-data.mdx
Fixes typo and makes statement grammatically correct.
> Fix typos & make statements grammatically correct

- src/features/landing/data/index.ts
- adds Optimism to Automation on docs homepage
> Add Optimism to Automation chains

- src/pages/getting-started/other-tutorials.mdx
- removes 404 links
- changes Keepers to Automation
> Update Learning Resources page

- src/pages/ccip/tutorials/programmable-token-transfers.mdx
- src/pages/ccip/tutorials/send-arbitrary-data.mdx
closes #1410
...
To Reproduce
Go to CCIP docs
then go the Transfer Token with Data tutorial
then go the step 4. Deploy your receiver contract on Polygon Mumbai:
then go to step 5. Enable your contract to receive CCIP messages from Ethereum Sepolia:
then go to step 6. Enable your contract to receive CCIP messages from the contract that you deployed on Ethereum Sepolia:
see error step 1. In Remix IDE, under Deploy & Run Transactions, open the list of transactions of your smart contract deployed on Ethereum Sepolia.
I think it should be Polygon Mumbai....
also same errors on Send Abitrary Data
Ethereum Sepolia --> Polygon Mumbai …
> chain-mix-up

- src/features/vrf/v2/components/CostTable.tsx
Feedback addressed an improvement that could be made on the textboxes of the VRF calculator to add commas as thousand separators as the user types big numbers.
Addressed and Applied the feedback.
> VRF calculator : Textboxes updated to include commas as they are completed

- public/samples/DataFeeds/DataConsumerV3.sol
- public/samples/DataFeeds/DataConsumerWithSequencerCheck.sol
- src/content/data-feeds/getting-started.mdx
Changed all references of old data feed function name getLatestData() to getChainlinkDataFeedLatestAnswer(), as agreed internally for tracking purposes
...
> modified function names to new agreed format

- package-lock.json
- package.json
Closes [FRONT-4292](https://smartcontract-it.atlassian.net/browse/FRONT-4292)
Updates Astro from `2.10.1` to `2.10.15`. This fixes an issue with custom elements that was showing in build previews.
> Update Astro to 2.10.15

- package-lock.json
- package.json
- src/components/Header/AlgoSearch/SearchModal.tsx
> New design testing and fixes

- src/content/quickstarts/dev3-chainlink-sdk.mdx
Specifically this section is updated: https://documentation-git-fork-thedriftofwords-qs-fix-1-chainlinklabs.vercel.app/quickstarts/dev3-chainlink-sdk#consuming-data-feeds
> Updates Dev3 SDK QS

- package-lock.json
- package.json
- src/components/Header/NavBar.tsx
- src/components/Header/useNavBar/navBarStore.ts
- src/components/Quickstart/Quickstart.astro
- src/components/Quickstart/StickyHeaderObserver.tsx
- src/components/Quickstart/stickyHeaderObserver.module.css
Closes [FRONT-4328](https://smartcontract-it.atlassian.net/browse/FRONT-4328)
Use @chainlink/components `0.3.3`, which includes a new `NavBar` featuring a callback to run when it changes its hiding state.
> Use @chainlink/components 0.3.3

- package-lock.json
- package.json
- src/components/Header/NavBar.tsx
- src/components/Header/getNavigationProps.ts
Part of NavBar QA
...
- Updates to @chainlink/components[ 0.4.1 version](https://github.com/smartcontractkit/explorer/pull/3754)
- New version takes props for productsNav and subProducstNav. This PR implements passing these props for both general docs page and also quickstarts section
- New config allows to add a navigation in homepage. 
...
- High level
- changes that
- you made
- ...
> Update to latest components, adds config

- src/components/Header/Header.astro
Re-enables Weglot for website translation
> Enable Weglot

- src/components/Header/AlgoSearch/SearchModal.tsx
Re-enables Algovera ai search
- Re-enables Algovera ai search
> re-enable ai search

- src/content/any-api/get-request/examples/multi-variable-responses.mdx
- src/content/any-api/get-request/examples/single-word-response.mdx
- src/content/chainlink-nodes/node-versions.mdx
- src/content/chainlink-nodes/oracle-jobs/all-jobs.mdx
- src/content/chainlink-nodes/oracle-jobs/all-tasks.mdx
Updates placeholder formatting in examples to remove the use of "<" or ">" which is reserved for codeblocks in the translation engine.
> Update placeholder formatting

- src/content/vrf/v2/getting-started.mdx
Add missing variable explanations in https://docs.chain.link/vrf/v2/getting-started
> Add missing contract variables

- package.json
- src/components/Header/AlgoSearch/SearchModal.tsx
Update Algovera to v0.0.80, change default search option to standard search.
> Change search default option

- src/content/chainlink-nodes/contracts/forwarder.mdx
- src/content/chainlink-nodes/contracts/operator.mdx
- src/content/chainlink-nodes/contracts/ownership.mdx
closes #1610
The `ConfirmedOwnerWithProposal.sol` contract's github url is invalid
Update `ConfirmedOwnerWithProposal.sol` contract github url
> fix contracts links

- src/content/vrf/v2/getting-started.mdx
- updates VRF Getting Started YouTube video link
> Change VRF video link

- src/components/RightSidebar/MoreMenu.astro
- src/content/chainlink-nodes/v1/configuration.mdx
- src/content/chainlink-nodes/v1/node-config.mdx
Update notation for filenames to use all caps to match style elsewhere and aid translations.
> Update notation for filenames

- src/content/chainlink-functions/getting-started.mdx
- src/content/chainlink-functions/tutorials/api-custom-response.mdx
- src/content/chainlink-functions/tutorials/api-post-data.mdx
- src/content/chainlink-functions/tutorials/api-use-secrets.mdx
Updates notation for codeblocks to allow translation.
> Update notation and breaks for codeblocks

- src/content/chainlink-functions/resources/secrets.mdx
Add line breaks around angle bracket usage on https://docs.chain.link/chainlink-functions/resources/secrets to allow translation.
> Update formatting for bracket usage

- src/features/notifications/data/index.ts
> update docs banner

- src/content/chainlink-automation/guides/compatible-contracts.mdx
~~**IMPORTANT: Please do not create a Pull Request without creating an issue first.Any change needs to be discussed before proceeding.**~~
Spelling fixes needn't be discussed.
Fix spelling mistake in documentation.
...
> Fix typo in compatible-contracts.mdx

- src/features/chainlink-automation/data/chainlink-automation-config.json
> update Fuji for Automation

- src/content/chainlink-functions/api-reference/javascript-source.mdx
...
...
- High level
- changes that
- you made
- ...
> Added a section to specify buffer return type

- src/content/chainlink-functions/getting-started.mdx
- adds YT video to Functions Getting Started Guide
> Update Functions Video

- src/config/data/ccip/v1_0_0/testnet/lanes.json
- src/config/data/ccip/v1_2_0/testnet/lanes.json
- src/config/data/ccip/v1_2_0/testnet/tokens.json
- adds USDC support for avax <> pol and pol <> optimism
> CCIP USDC lane updates

- src/content/chainlink-automation/concepts/automation-architecture.mdx
- src/content/chainlink-automation/overview/automation-economics.mdx
- update formatting for Automation billing page
> Update Automation billing page

- src/content/ccip/api-reference/client.mdx
None
Changes incorrect function description
Changes incorrect function description
> fix: incorrect function description

- src/content/quickstarts/batch-reveal.mdx
- src/content/quickstarts/giveaway.mdx
- src/content/quickstarts/hardhat-plugin.mdx
- src/content/quickstarts/time-based-upkeep.mdx
- src/content/quickstarts/vrf-enabled-lootbox-pack.mdx
- src/content/quickstarts/vrf-mystery-box.mdx
Content within `Tabs` and `TabsContent` components does not display when nested inside an `Accordion` so, temporarily removing all these instances until the bug is actually fixed with those components not working together
> QS: Temp bugfix for Accordion component

- src/content/chainlink-automation/guides/migrate-to-v2.mdx
Make forwarder info more prominent at intro
https://documentation-3z2wfuye5-chainlinklabs.vercel.app/chainlink-automation/guides/migrate-to-v2
> Add forwarder callout

- src/content/chainlink-automation/reference/debugging-errors.mdx
> Update Automation debugging script link

- public/samples/DataFeeds/DataConsumerWithSequencerCheck.sol
- src/content/chainlink-automation/overview/supported-networks.mdx
- src/content/data-feeds/l2-sequencer-feeds.mdx
- src/content/resources/link-token-contracts.mdx
- src/content/vrf/v2/direct-funding/supported-networks.mdx
- src/features/chainlink-automation/data/chainlink-automation-addresses.json
- src/features/chainlink-automation/data/chainlink-automation-config.json
- src/features/data/chains.ts
Support for the OP Goerli testnet will end on March 7th.
> Remove Optimism Goerli

- src/config/sidebar.ts
- src/content/chainlink-functions/api-reference/javascript-source.mdx
- Fix outdated module imports language
- Move up Service Limits to top section
> Functions docs small fixes

- src/content/vrf/v2-5/supported-networks.mdx
Corrections for Avalanche mainnet direct funding config, and Ethereum mainnet gas lanes
> V2.5 supported networks corrections

- src/content/chainlink-automation/concepts/best-practice.mdx
- src/content/chainlink-automation/overview/automation-release-notes.mdx
https://documentation-git-fork-thedriftofwords-062-c560a0-chainlinklabs.vercel.app/chainlink-automation/concepts/best-practice
https://documentation-git-fork-thedriftofwords-062-c560a0-chainlinklabs.vercel.app/chainlink-automation/overview/automation-release-notes#2024-06-21---deprecation-of-older-upkeeps
> Announce deprecation date for older upkeeps

- src/config/sidebar.ts
- src/content/chainlink-automation/concepts/best-practice.mdx
- src/content/chainlink-automation/guides/forwarder.mdx
- src/content/chainlink-automation/guides/manage-upkeeps.mdx
- src/content/chainlink-automation/guides/migrate-to-v2.mdx
- src/content/chainlink-automation/index.mdx
- src/content/chainlink-automation/overview/automation-economics.mdx
- src/content/chainlink-automation/overview/supported-networks.mdx
- src/features/chainlink-automation/common/ChainlinkAutomation.astro
- src/features/chainlink-automation/common/deprecation.mdx
- Add deprecation banner to relevant / highly visible pages
- Update mentions of 2.0 to 2.1
https://documentation-git-fork-thedriftofwords-cla-f01d3c-chainlinklabs.vercel.app/chainlink-automation
https://documentation-git-fork-thedriftofwords-cla-f01d3c-chainlinklabs.vercel.app/chainlink-automation/guides/migrate-to-v2
> CLA deprecation banner

- src/content/chainlink-functions/supported-networks.mdx
https://documentation-git-fork-thedriftofwords-071-4afe69-chainlinklabs.vercel.app/chainlink-functions/supported-networks
Corrections for the billing tables to sync with RDD
> Functions: Update supported networks page

- src/content/chainlink-automation/overview/automation-economics.mdx
> docs: typo in automation-economics.mdx

- src/config/sidebar.ts
- src/content/ccip/tutorials/index.mdx
- src/content/ccip/tutorials/send-arbitrary-data-receipt-acknowledgment.mdx
- src/content/ccip/tutorials/send-arbitrary-data.mdx
Clarify in the title that this [guide](https://docs.chain.link/ccip/tutorials/send-arbitrary-data-receipt-acknowledgment) is about sending and receiving data from the receiver : A -> B -> A
> Clarify title of CCIP guide 

- src/features/landing/data/index.ts
https://documentation-git-landing-page-fix-chainlinklabs.vercel.app/
> Add BASE logo to VRF landing page card

- src/components/PageTabs.astro
- src/components/QuickLinks/sections/ProductChainTable.module.css
Troubleshooting CSS caching issues
> Resolve CSS caching issues

- src/content/vrf/v2-5/overview/direct-funding.mdx
closes #2059 
The "What's next" section on the page https://docs.chain.link/vrf/v2-5/overview/direct-funding pointed to v2 examples. 
I have updated them to link to v2.5 pages.
> Update direct-funding Links

- public/samples/CCIP/Messenger.sol
"aas" --> "as"
...
...
- High level
- changes that
- you made
- ...
> Typo corrected

- src/features/feeds/components/Tables.tsx
https://documentation-git-streams-feeds-tables-chainlinklabs.vercel.app/data-streams/stream-ids?network=arbitrum&page=1
> Feed tables update

- src/components/Header/Nav/navBar.module.css
- src/components/Header/aiSearch/Search.tsx
- src/components/Header/aiSearch/SearchButton.tsx
- src/components/Header/aiSearch/searchButton.module.css
This PR enables the search functionality on mobile
> Add search on mobile

- public/changelog.json
- src/components/QuickLinks/data/productChainLinks.ts
- src/features/feeds/components/Tables.module.css
- src/features/feeds/components/Tables.tsx
Reverts smartcontractkit/documentation#2145
> Revert "Data Streams - Solana"

- src/components/CCIP/Search/Search.css
- Fix bug with search index overlapping the "resources" dropdown
> Improve Search index

- src/components/Header/getNavigationProps.ts
- src/pages/index.astro
- Move Divider in dropdown to align with area separation
- Improve font and spacing on mobile
- Improve font and spacing on desktop
> Fix font issue

- public/samples/CCIP/Messenger.sol
- public/samples/CCIP/TokenTransferor.sol
- public/samples/CCIP/usdc/Receiver.sol
- src/content/chainlink-local/build/ccip/hardhat/local-simulator-fork.mdx
...
fix some comments
- High level
- changes that
- you made
- ...
> chore: fix some comments

- src/content/data-feeds/ens.mdx
- src/content/resources/glossary.mdx
This pull request includes minor modifications to improve readability and consistency in documentation files (`ens.mdx` and `glossary.mdx`).
**bsrc/content/data-feeds/ens.mdx**
- `libraries libraries that ` → `libraries that `
**src/content/resources/glossary.mdx**
- `Confrimations ` → `Confirmations `
> Fix errors in documentation files 

- src/content/chainlink-local/build/ccip/foundry/cct-burn-and-mint-fork.mdx
- src/content/chainlink-local/build/ccip/foundry/cct-lock-and-release-fork.mdx
This PR migrates Chainlink Local CCT guides to v1.5.1
> Migrate Chainlink Local CCT guides to v1.5.1

- src/content/ccip/concepts/cross-chain-tokens.mdx
Update sections for 1.5.0 token pools to discuss limitations for decimals
https://smartcontract-it.atlassian.net/browse/DOC-684
> Gfletcher cll token pools

- src/components/Header/Nav/ProductNavigation/Mobile/MegaMenu.tsx
- Update two links on the mobile megamenu that were wrongly set
> Fix megamenu links on mobile

- src/content/any-api/api-reference.mdx
- src/content/any-api/find-oracle.mdx
- src/content/any-api/get-request/examples/array-response.mdx
- src/content/any-api/get-request/examples/existing-job-request.mdx
- src/content/any-api/get-request/examples/large-responses.mdx
- src/content/any-api/get-request/examples/multi-variable-responses.mdx
- src/content/any-api/get-request/examples/single-word-response.mdx
- src/content/any-api/get-request/introduction.mdx
- src/content/any-api/getting-started.mdx
- src/content/any-api/introduction.mdx
- src/content/any-api/testnet-oracles.mdx
- src/content/architecture-overview/architecture-overview.mdx
- src/features/any-api/common/AnyApiCallout.astro
- src/features/any-api/common/UseFunctions.mdx
https://documentation-git-any-api-fix-chainlinklabs.vercel.app/any-api/introduction
> Stronger Functions banners in Any API pages

- src/components/CCIP/Chain/Chain.astro
- src/components/CCIP/Landing/ccip-landing.astro
update CCIP Add a Token link to direct users to Token Manager document.
> add token link

- src/components/CCIP/Drawer/LaneDrawer.tsx
- src/components/CCIP/Drawer/TokenDrawer.tsx
Update the tool tip for the table column header “Mechanism” on a lane from "Token pooling mechanism" -> "Token handling mechanism".
> Update LaneDrawer & TokenDrawer

- src/scripts/link-check/linkcheck.ts
This pull request includes changes to the `checkChunkFile` function in `src/scripts/link-check/linkcheck.ts` to enhance the logging and handling of output data from the link checker process. The most important changes include capturing stdout and stderr output, filtering specific warnings, and treating certain warnings as non-blocking.
Enhancements to logging and output handling:
* [`src/scripts/link-check/linkcheck.ts`](diffhunk://#diff-ad87a50f9d54085b8aa77bdcf4c33059e672fc5348d853722a6f4c078fa7ded9L170-R207): Modified the `checkChunkFile` function to capture stdout and stderr output into a variable `outputData` for further processing.
Improved warning handling:
* [`src/scripts/link-check/linkcheck.ts`](diffhunk://#diff-ad87a50f9d54085b8aa77bdcf4c33059e672fc5348d853722a6f4c078fa7ded9L170 …
> Update linkcheck script

- src/components/CCIP/Landing/NetworkGrid.tsx
2 rows x 8 items - 2 rows x 7 items
> fix error NetworkGrid.tsx

- src/components/CCIP/TokenGrid/TokenGrid.tsx
`7` rows x 4 items - `6` rows x 4 items
> fix error TokenGrid.tsx

- src/components/CCIP/ChainHero/ChainHero.tsx
> fix ChainHero.tsx

- src/components/Footer/Footer.astro
add link to the quick links for builders to the footer under the Developer section
> add quick links to the footer

- src/content/data-feeds/svr-feeds/index.mdx
Does not close an issue, only fixes a typo. 
Fixes a typo on the SVR documentation
> Fix SVR typo

- src/components/Header/Nav/ProductNavigation/Desktop/megaMenu.module.css
- src/components/Header/Nav/ProductNavigation/Desktop/productNavigation.module.css
- src/scripts/chainlink-automation/networks-config.ts
- src/scripts/helper/find-nonchecksummed-addresses.ts
This pull request addresses several typographical errors in both CSS and TypeScript files within the project. The changes include:
1. **CSS Files:**
- Corrected the spelling of "available" in comments within `megaMenu.module.css` and `productNavigation.module.css`.
2. **TypeScript Files:**
- Fixed the spelling of "retrieving" in an error message within `networks-config.ts`.
- Corrected the spelling of "occurrences" in an error message within `find-nonchecksummed-addresses.ts`.
These changes improve code readability and maintainability by ensuring that comments and error messages are free of spelling mistakes.
> Fix Typographical Errors in CSS and TypeScript Files

- public/llms.txt
adding llms.txt file to root to help support developers using LLMs
>  add llms txt file to root

- src/content/data-streams/reference/streams-direct/streams-direct-rust-sdk.mdx
- src/content/data-streams/tutorials/streams-direct/streams-direct-api-rust.mdx
- src/content/data-streams/tutorials/streams-direct/streams-direct-api-rwa-rust.mdx
- src/content/data-streams/tutorials/streams-direct/streams-direct-ws-rust.mdx
- src/content/data-streams/tutorials/streams-direct/streams-direct-ws-rwa-rust.mdx
This pull request updates multiple Rust-based tutorials for Chainlink Data Streams. The changes span across tutorials for different use cases (Direct API, WebSocket, and RWA streams) and include dependency updates, namespace replacements, and minor code improvements.
* Updated `Cargo.toml` dependencies to use `chainlink-data-streams-sdk` and `chainlink-data-streams-report` version `1.0.0`, replacing the old Git-based dependencies. [[1]](diffhunk://#diff-fbee6d6b248f3af3ecfbaaf0c0e88bce47abb515c385554da5c831fa5779b886L71-R75) [[2]](diffhunk://#diff-2bf2d37b89bf984eb5dc688f335ab122e082155176a97e49510ba9a56f280c27L71-R75) [[3]](diffhunk://#diff-34540b6c95e54681ab75617412fb3360d6b06e9e23d13838d20d02b9796c66b2L68-R72) [[4]](diffhunk://#diff-86eb21593ddd4c65fc0c74e974a80e50524a6197783f015cf5cf88 …
> DS - Update Rust SDK imports to use official crates

- src/content/data-feeds/svr-feeds/index.mdx
Add new SVR feeds
Add the 3 added feeds to https://docs.chain.link/data-feeds/svr-feeds#4-detect-svr-enabled-feeds-for-the-aave-protocol. 
[See here](https://documentation-git-chore-add-3-extra-svr-fe-b4ddf9-chainlinklabs.vercel.app/data-feeds/svr-feeds#4-detect-svr-enabled-feeds-for-the-aave-protocol)
> Chore: add 3 new Aave-enabled SVR feeds to SVR docs

- src/content/data-feeds/l2-sequencer-feeds.mdx
> add celo to l2eps

- package-lock.json
- package.json
- src/features/ccip/api-reference-callout/ImportCCIPPackage160.mdx
- src/features/chainlink-local/api-reference-callout/ImportPackage025.mdx
...
...
- High level
- changes that
- you made
- ...
> Updated contracts-ccip to 1.6.0-latest

- src/content/chainlink-functions/resources/simulation.mdx
add additional caution note about Chainlink Functions Toolkit NPM package
> add caution note about BETA

- src/config/sidebar.ts
- src/content/data-feeds/tron/index.mdx
- src/content/data-feeds/using-data-feeds.mdx
This pull request introduces a new tutorial for integrating Chainlink Data Feeds on the TRON blockchain and updates the sidebar configuration to include a new section for TRON guides. The tutorial provides comprehensive guidance on deploying smart contracts using TronBox, interacting with them off-chain using TronWeb, and utilizing Chainlink price feeds on the TRON Nile Testnet.
* Added a new section titled "Tron Guides" to the `SIDEBAR` configuration, linking to the tutorial on "Data Feeds on Tron." (`src/config/sidebar.ts`)
* Created a detailed step-by-step guide for using Chainlink Data Feeds on the TRON blockchain, covering smart contract development, off-chain interaction, and TRON-specific setup requirements. (`src/content/data-feeds/tron/index.mdx`)
> Tron data feeds

- src/components/Header/Nav/ProductNavigation/Desktop/ProductNavigation.tsx
- src/components/Header/Nav/ProductNavigation/Mobile/ProductNavigation.tsx
add back "Get Certified" to product nav leading to new Certification page.
> Certification

- .github/dependabot.yml
- package-lock.json
- package.json
- src/components/Header/aiSearch/Search.css
- src/components/Header/aiSearch/Search.tsx
> Search upgrade to 0.11.3 and CSS fix

- package-lock.json
- package.json
> Update Search to 0.11.4

- public/changelog.json
- src/content/chainlink-nodes/v1/node-config.mdx
- src/content/chainlink-nodes/v1/running-a-chainlink-node.mdx
- src/content/chainlink-nodes/v1/secrets-config.mdx
For release 2.26:
- Update [node config](https://docs.chain.link/chainlink-nodes/v1/node-config) for 2.26
- Update [secrets config](https://docs.chain.link/chainlink-nodes/v1/secrets-config) for 2.26
- Update [changelog](https://dev.chain.link/changelog)
- Update [running a node guide](https://docs.chain.link/chainlink-nodes/v1/running-a-chainlink-node)
Backfills:
- changelog backfilled 2.25
> Node 2.26 Release

- src/content/ccip/ccip-execution-latency.mdx
Polygon is using finality depth instead of tag so it needs to be updated in Docs
> Update Polygon Finality info

- public/changelog.json
- src/components/QuickLinks/data/productChainLinks.ts
- src/features/data/chains.ts
- src/scripts/data/detect-new-data.ts
> DF: Plasma integration
