smartcontractkit/documentation

docs/Additional Information/faq.md, docs/Additional Information/glossary.md, docs/Contract Creators/addresses-and-job-ids.md, docs/Data Provider Nodes/bookmaker-ratings-oracle.md, docs/Data Provider Nodes/chainlink-alarm-clock.md, docs/Data Provider Nodes/ciphertrace-defi-compli-oracle.md, docs/Data Provider Nodes/dns-ownership-oracle.md, docs/Data Provider Nodes/dxfeed-oracle.md, docs/Data Provider Nodes/finage-global-market-data-oracle.md, docs/Data Provider Nodes/flightaware-chainlink-testnet.md, docs/Data Provider Nodes/genesis-volatility.md, docs/Data Provider Nodes/geodb-oracle-node.md, docs/Data Provider Nodes/kraken-rates-oracle-node.md, docs/Data Provider Nodes/lcx-testnet.md, docs/Data Provider Nodes/therundown-oracle-node.md, docs/Data Provider Nodes/tiingo-eod-stock-price-oracle.md, docs/Data Provider Nodes/watchsignals.md, docs/Node Operators/best-security-practices.md, docs/Node Operators/miscellaneous.md, docs/Oracle Jobs/adapters.md, docs/Oracle Jobs/initiators.md, docs/Using Any API/decentralized-oracles-ethereum-mainnet.md
=> Fix anchors path

_includes/feed.liquid
Fix #48
This does not add any UI for showing users anchors, this will come later.
=> add anchors to feeds and pairs

docs/Data Provider Nodes/data-provider-nodes-list.md
Based on the team's feedback, `data category` is a crucial piece of information when understanding which information a particular provider can feed to the contract.
=> Add data categories for data provider nodes list

docs/Additional Information/faq.md
Often asked question on the Discord>
Also slightly edited the Bytes32 question.
=> Add Multi-Word-Response Q&A

_data/navigation.js
Remove backslash typo on node-operators sidebar
=> Remove backslash typo on node-operators sidebar

docs/Using Any API/existing-job-request.md, docs/Using Any API/make-a-http-get-request.md
Whilst this line is not strictly necessary for v0.6 contracts, later versions of Solidity have removed the inheritance of `using` statements by default. 
Users who copy and paste this code into a newer version of Solidity are prompted with a compilation error.
=> Explicit using statement on Any API contracts

docs/Oracle Jobs/adapters.md, firebase.json
Put old URL in firebase.json so backlinks still work.
=> Changed Core Adapters primary URL

docs/Introduction/tutorials/intermediates-tutorial.md, docs/Using Randomness/chainlink-vrf-api-reference.md, docs/Using Randomness/get-a-random-number.md
`userProvidedSeed` has been depreciated in the `VRFConsumerBase`, updating codebase to reflect this. 
See: https://github.com/smartcontractkit/chainlink/commit/ba36ffd8afa1341db436dc4e7270e05cef6b87cd#diff-15e43cddffadbb6956575a778e4ae0675b05999da711afb0da833666edb4d221
=> added change to VRF

docs/Node Operators/running-a-chainlink-node.md
- Convert tabbed code blocks to Markdown format. Markdown ignores tabbed code blocks in this format. See https://docs.chain.link/docs/running-a-chainlink-node/
- Trim unnecessary extra spaces at ends of lines
- Add newline at EOF
=> Fix broken tabbed code blocks. Minor cleanup.

docs/Introduction/tutorials/intermediates-tutorial.md
The link in the documentation to the evm-contracts library is broken. This change is to point to the current location of the chainlink contracts.
=> Fix broken link to chainlink contract library

docs/Using Price Feeds/feed-registry.html
Updates the link to `Denominations.sol`. The contract has been moved from the `dev/` directory https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/Denominations.sol
=> Fix broken Denominations link

docs/Additional Information/api-reference.md, docs/Chainlink Node API/chainlink-node-api-reference.md, docs/Introduction/architecture-overview/architecture-request-model.md, docs/Node Operators/configuration-variables.md, docs/Using Any API/chainlink-framework.md, docs/Using Price Feeds/get-the-latest-price.html, docs/Using Price Feeds/price-feeds-api-reference.md, docs/Using Price Feeds/reference-contracts.md, docs/Using Randomness/chainlink-vrf-api-reference.md, docs/Using Randomness/vrf-contracts.md
Pages for API References and Contract Addresses are named generic. This causes confusing search results and weakens our SEO. This PR fixes that.
=> Fix api references and contracts titles

docs/Contract Creators/l2-sequencer-flag.md
Majority of developers reaching this page are interested in knowing how to write a safe contract on L2. It would be a lot clearer to only list the Sequencer Health Flags contract addresses here.
If use cases arise for knowing the sequencer state from Ethereum we can add the feed addresses back.
=> Removing L1 contract addresses from L2 Sequencer Health Docs

docs/Developer Reference/link-token-contracts.md
Avalanche Mainnet has no particular name, Fuji is the name of the Testnet.
=> Fix Avalanche Mainnet name

docs/Data Provider Nodes/chainlink-alarm-clock.md, docs/Data Provider Nodes/dns-ownership-oracle.md, docs/Data Provider Nodes/finage-global-market-data-oracle.md, docs/Data Provider Nodes/google-weather.md, docs/Data Provider Nodes/kraken-rates-oracle-node.md, docs/Data Provider Nodes/lcx-testnet.md, docs/Developer Reference/user-guides/deploy-your-first-contract.md, docs/Introduction/tutorials/advanced-tutorial.md, docs/Introduction/tutorials/beginners-tutorial.md, docs/Introduction/tutorials/intermediates-tutorial.md, docs/Node Operators/fulfilling-requests.md, docs/Using Any API/existing-job-request.md, docs/Using Any API/large-responses.md, docs/Using Any API/make-a-http-get-request.md, docs/Using Any API/multi-variable-responses.md, docs/Using Price Feeds/feed-registry.html, docs/Using Price Feeds/get-the-latest-price.html, docs/Using Price Feeds/historical-price-data.html, docs/Using Randomness/get-a-random-number.md, docs/chainlink-keepers/compatible-contracts.md
The samples at https://docs.chain.link/samples/ are not functioning properly in Remix URLs.
Change these URLs back to GitHub for now until we can resolve the issue.
=> Change ./samples/ links to point to the GitHub URLs.

_includes/feed.liquid, docs/Using Price Feeds/get-the-latest-price.html
- Add a Solana network examples section with links to the GitHub Solana demo.
- Update the URLs to direct customers to the Solana Network Examples section.
Next steps will be to pull the documentation out of GitHub into a full set of documentation for the Solana demo with code sample explanations.
=> Add basic support for Solana Devnet in our documentation.

docs/Using Randomness/chainlink-vrf.md
Defining RNG before using the acronym
=> very small grammatical fix on RNG 

_data/navigation.js, _includes/feed.liquid, docs/Using Price Feeds/get-the-latest-price-solana.md, docs/Using Price Feeds/get-the-latest-price.html
Sharing this draft to get feedback.
Changes:
- Split "Getting Price Feeds" into two documents. One document is for EVM, and another for Solana.
- Expand on the process documented in the README files
- Provide additional conceptual information and links to relevant Solana documentation.
- Walk through the main components of the code to explain the logic.
=> Add expanded documentation for Solana data feeds.

.github/workflows/check-links.yml
Starting with a scheduled job.
We should be checking this as a standard CI check for every PR, but it's not clear how to spin up a local instance in a clean way.
=> add scheduled link checking to CI

.github/workflows/build.yml, .github/workflows/process-feeds.yml, .github/workflows/test.yml
This increases security by not allowing the code we execute to change.
Action devs can change tags, but they can't change the code for a sha.
Fixes #71
=> move all actions to shas

_src/docs.css
Fixes #375
Long page titles and also narrow browser windows were causing doc satisfaction stars to wrap.
Staging: https://deploy-preview-378--dreamy-villani-0e9e5c.netlify.app/docs/hackathon-rules-waiver-release-and-code-of-conduct/
=> Prevent docsat stars from wrapping when page titles are very long.

_includes/main.liquid, _src/docs.css
- Add a 2021-09-17 to 2021-10-21 notice to sign up.
- Add a 2021-10-22 to 2021-11-28 notice that the hackathon is ongoing.
- Remove previous events.
If the banner doesn't appear in the preview, open the preview in a private tab.
Preview: https://deploy-preview-380--dreamy-villani-0e9e5c.netlify.app
=> Add a banner for the Fall 2021 Hackathon.

_includes/main.liquid
- Re-word the banner text to match the banner on https://chain.link.
- Change the dates for the second banner.
=> Modify the Fall 2021 Hackathon banner.

_data/navigation.js, docs/Node Operators/best-practices-aws.md
- Clean up navigation.js
- Add navigation for Best Practices for Deploying Nodes on AWS
- Add cross-linking from the Best Practices doc to the AWS Quickstart for Chainlink nodes
=> Clean up navigation and add AWS best practices.

docs/Using Price Feeds/get-the-latest-price-solana.md
adding a backlink to the new solana blog post on our Solana docs page. Helps with SEO
=> adding link to solana blog post on Solana docs page

docs/chainlink-keepers/faqs.md
Remove extra period sign in the following section of the Chainlink Keepers FAQ:
What gas price does the Keeper use to trigger the function?
"[...] at preset block intervals until it observes the corresponding transaction event.**.**"
=> Docs: Remove extra dot in the Chainlink Keepers FAQ.

.github/workflows/check-links.yml
Right now our schedule linkchecker fails with:
```Provided URLs failing:
https://docs.chain.link/%20-e (HTTP 404)
Stats:
0 links
1 destination URLs
0 URLs ignored
0 warnings
1 errors
```
This attempts to fix this by moving to the latest version
=> attempt to fix multiple arguments support via latest sha

_src/deploy-to-github.js, docs/Data Provider Nodes/chainlink-alarm-clock.md, docs/Data Provider Nodes/dns-ownership-oracle.md, docs/Data Provider Nodes/finage-global-market-data-oracle.md, docs/Data Provider Nodes/google-weather.md, docs/Data Provider Nodes/kraken-rates-oracle-node.md, docs/Data Provider Nodes/lcx-testnet.md, docs/Developer Reference/user-guides/deploy-your-first-contract.md, docs/Introduction/tutorials/advanced-tutorial.md, docs/Introduction/tutorials/beginners-tutorial.md, docs/Introduction/tutorials/intermediates-tutorial.md, docs/Node Operators/fulfilling-requests.md, docs/Using Any API/existing-job-request.md, docs/Using Any API/large-responses.md, docs/Using Any API/make-a-http-get-request.md, docs/Using Any API/multi-variable-responses.md, docs/Using Price Feeds/feed-registry.html, docs/Using Price Feeds/get-the-latest-price.html, docs/Using Price Feeds/historical-price-data.html, docs/Using Randomness/get-a-random-number.md, docs/chainlink-keepers/compatible-contracts.md
- Remove hard-coded Solidity versions from Remix links. Allow Remix to automatically select the compiler version from `pragma`.
- Update the version numbers for https://github.com/smartcontractkit/chainlink/blob/master/contracts/ files where necessary.
- Auto-remove trailing whitespace.
=> Remove hard-coded Solidity versions from Remix links.

docs/Introduction/tutorials/intermediates-tutorial.md
Typo: "depreciated" instead of "deprecated"
=> Fix typo in documentation

docs/External Initiators/external-initiators-in-nodes.md, docs/External Initiators/external-initiators-introduction.md
There is no mention on the page or on the external initiator topic that it is necessary to enable the flag FEATURE_EXTERNAL_INITIATORS=true on the .env file of the node. I'm sure other people got stuck on this like me for quite some time.
=> Mention FEATURE_EXTERNAL_INITIATORS

_tools/networks.ts, docs/Developer Reference/link-token-contracts.md
Ava Labs recently announced Snowtrace. A blockchain explorer build a la Etherscan that will replace the old cchain.explorer .
https://medium.com/avalancheavax/snowtrace-bringing-etherscan-to-the-avalanche-community-f8463e0d80d3
The old one (used at the moment in this doc) will be deprecated in a few days.
https://testnet.snowtrace.io/
https://snowtrace.io/
=> feat: Update avalanche explorer link to Snowtrace

_data/navigation.js, _tools/networks.ts, docs/Using Price Feeds/data-feeds-moonriver.md
Data feed tables generate after the merge. Looks good locally testing.
Preview here: https://deploy-preview-525--dreamy-villani-0e9e5c.netlify.app/docs/data-feeds-moonriver/
=> Add Moonriver data feeds

_data/navigation.js, _tools/networks.ts, docs/Developer Reference/link-token-contracts.md, docs/Using Price Feeds/reference-contracts.md, docs/Using Randomness/vrf-contracts.md, docs/Using Randomness/vrf-security-considerations.md
- Update Polygon https://wallet.matic.network URLs to https://wallet.polygon.technology.
- Update Polygon explorer URLs.
- Move Terra and Solana data feeds navigation exclusively to non-EVM section.
- Add Moonriver link to the reference contracts overview.
=> Update links and navigation.

docs/Oracle Jobs/migration-v1-v2.md
In migration-v1-v2.md
line 111
- In v1, the job ID is randomly generated at creation time. In v2 jobs, the job ID can be manually specified or the Chainlink node will automatically **generate** it.
changed generated => generate
=> corrected typo (generated => generate

_tools/networks.ts, docs/Solana/DataFeeds/using-data-feeds-solana.md, docs/Solana/overview.md
Addresses https://github.com/smartcontractkit/documentation/issues/510, to use [Solscan](https://solscan.io/) as the default explorer for Solana data feeds
=> Update explorer to solscan

docs/Using Randomness/chainlink-vrf-api-reference.md
Docs [here](https://docs.chain.link/docs/chainlink-vrf-api-reference/#requestrandomness) mention `external` function type for `fulfillRandomness`.
If this function definition is used, it could ofc have security implications allowing an external malicious call with pre-cooked input.
=> Replace fulfillRandomness external with internal function type

_tools/process-data.ts
This is required to correctly process the new Solana Devnet feeds. The docs are [currently hard-coded](https://github.com/smartcontractkit/documentation/blob/main/docs/Solana/DataFeeds/data-feeds-solana.md?plain=1), so this PR does not affect them.
We already use `docsHidden` for Proxy addresses, so this PR just applies them to Contract addresses.
`transmissionsAccount` is required to correctly process the new Solana feeds.
=> Enable docsHidden and transmissionsAccount on process-data.ts

docs/Solana/DataFeeds/using-data-feeds-solana.md
New examples have dependencies that require a C compiler.
=> Add a C compiler as a requirement for the Solana example

docs/Node Operators/configuration-variables.md
Documents environment variables add by https://github.com/smartcontractkit/chainlink/pull/5887
Though I don't think that PR has made it to an official release yet. Should this PR be against a different branch? `release/1.2.0` perhaps?
=> Document new telemetry ingress env vars

docs/Chainlink Node API/chainlink-node-api-reference.md, docs/Node Operators/configuration-variables.md, firebase.json
This page is not useful. Remove it and point to the config page which has at least some relevant information.
=> Remove misleading API reference page and redirect to node configuration

docs/Node Operators/configuration-variables.md
The `minimumContractPayment` var applies to more chains than ETH mainnet. https://github.com/smartcontractkit/chainlink/blob/120d9ff657dfd11c6eaaf581e13f4aaf947bd692/core/chains/evm/config/chain_specific_config.go#L152
Update the docs with the correct list.
=> Config vars: List chains where the default minimumContractPayment is 0.1

docs/Using Price Feeds/get-the-latest-price.html
Fix following the bug introduced by PR #651
=> Fix markdown header formatting in Using Data Feeds

_includes/samples/events/avasummit/VRFv2SubscriptionManager.sol, docs/events/avasummit/overview.md
Reverts smartcontractkit/documentation#698
Some users still need the VRF examples. Revert #698 and remove the non-VRF content.
=> Revert "Remove Avasummit 2022 page"

docs/Oracle Jobs/Job Types/direct_request.md
@boxhock noticed that `requesters` and `minContractPaymentLinkJuels` were undocumented. This change adds the examples from the v0.10.14 changelog: https://github.com/smartcontractkit/chainlink/blob/develop/docs/CHANGELOG.md#requestersmincontractpaymentlinkjuels
Towards #382
=> direct request: document requesters and minContractPaymentLinkJuels

docs/Oracle Jobs/Job Types/offchain_reporting.md
Documenting https://github.com/smartcontractkit/chainlink/pull/6423 and targeting `1.4`.
=> Adds minor doc for `evmChainID` on OCR jobs

docs/Introduction/getting-started/conceptual-overview.md
Solidity supports only `private`, `internal` and `public` visibility for state variables.
Only functions can have `external` visibility.
=> Remove external state variable visibility

docs/Node Operators/configuration-variables.md
This was deprecated with `v0.10.8`, and removed from the code completely since.
> - It is no longer required to set `DEFAULT_HTTP_ALLOW_UNRESTRICTED_NETWORK_ACCESS=true` to enable local fetches on bridge or http tasks. If the URL for the http task is specified as a variable, then set the AllowUnrestrictedNetworkAccess option for this task. Please remove this if you had it set and no longer need it, since it introduces a slight security risk.
From https://github.com/smartcontractkit/chainlink/blob/develop/docs/CHANGELOG.md#0108---2021-06-21
=> remove DEFAULT_HTTP_ALLOW_UNRESTRICTED_NETWORK_ACCESS

docs/Using Randomness/vrf-contracts.md
closes #816
Add to wallet button missing next to Link contract address for Fantom mainnet
- Update the VRF contract addresses page
=> Add to wallet for fantom mainnet in VRF contract page

_src/reference/chains.json, _src/reference/linkNameSymbol.json, docs/Developer Reference/link-token-contracts.md
Metis chains was added to supported networks. However, chains.json & linkNameSymbol.json were not updated. Thus, not allowing users to add metis token to their metamask wallet from docs.chain.link
=> Add Metis to wallet

docs/Node Operators/miscellaneous.md
This PR add documentation for the multiuser and role based access control functionality in the core node: https://github.com/smartcontractkit/chainlink/pull/6843
The core node will now optionally support multiuser sessions with role backed authorization. Update documentation with usage examples and state what each role can do.
This PR adds a section on the miscellaneous page describing how to set it up and enumerates all actions that each role is permitted to do.
=> Add new section in documentation for explanation, examples, and permissions set of optional multiuser and RBAC functionality

_data/navigation.js, docs/Oracle Jobs/Task Types/task_base64encode.md, docs/Oracle Jobs/Task Types/task_hexencode.md
closes https://app.shortcut.com/chainlinklabs/story/48275/create-hexencode-base64encode-tasks
Add documentation for two new pipeline tasks: hexencode and base64encode
* Two new documentation pages: task_hexencode.md and task_base64encode.md
* Updated navigation.js
=> Add docs for new pipeline tasks: hexencode and base64encode

docs/Developer Reference/link-token-contracts.md
closes https://app.shortcut.com/chainlinklabs/story/50340/display-addresses-in-checksummed-form-in-docs-chain-link
setChainlinkToken() call only accepts addresses in checksummed format. Our docs page has mixed formats so let's make it consistent. It'll make it easier to copy-paste into Solidity code (including some of our examples)
- Convert Mainnet and Goerli LINK token contract addresses to checksummed format (using ethers.utils.getAddress())
- List Goerli as the first testnet on the page (other testnets will be deprecated soon).
=> Show LINK contract addresses in checksummed form

docs/Using Price Feeds/using-chainlink-reference-contracts.md
fix name of chainlink NPM package
...
`chainlink` isn't the name of the package, `@chainlink/contracts` is the name.
=> fix name of chainlink NPM package

docs/chainlink-nodes/best-security-practices.md, docs/resources/example-projects.md
closes #859
It could be helpful for new node operators or existing operators not taking an IaC. With those modules, it's possible to create highly available, fault-tolerant, and scalable serverless infrastructure on AWS for both Chainlink OCR node and Chainlink External Adapters.
Used by Orion operator on Eth mainnet and reviewed by Mycelium and Chorus operators.
- added links to Terraform modules for serverless setup for Chainlink OCR node and adapters on AWS
=> add links for IaC solutions

docs/any-api/data-providers/dns-ownership.md, docs/data-feeds/l2-sequencer-feeds.md, docs/getting-started/consuming-data-feeds.md, docs/getting-started/deploy-your-first-contract.md, docs/resources/link-token-contracts.md, docs/vrf/v2/examples/get-a-random-number.md
- Add L2 sequencer feed testnet addresses
- Clean up the Link Token Contracts page
=> Add L2 sequencer feed testnets and edit Link Token Contracts

docs/any-api/api-reference.md
closes #925 
Document missing functions in the ANY API api reference
=> Document chainlinkClient operator functions

_includes/sections/vrf-v2-common.md, docs/vrf/v2/best-practices.md, docs/vrf/v2/examples/get-a-random-number.md, docs/vrf/v2/examples/programmatic-subscription.md, docs/vrf/v2/introduction.md, docs/vrf/v2/migration-from-v1.md, docs/vrf/v2/security.md, docs/vrf/v2/supported-networks.md
=> VRF v2 rework confusing steps in programmatic examples

docs/chainlink-keepers/compatible-contracts.md
Is currently plural, but the actual contract / interfaces are singular.
=> fix typo in interface names

_data/navigation.js, docs/chainlink-nodes/configuration-variables.md, docs/chainlink-nodes/node-versions.md, docs/chainlink-nodes/oracle-jobs/task-types/task_base64encode.md, docs/chainlink-nodes/oracle-jobs/task-types/task_hexencode.md
- hexencode and base64encode tasks: https://github.com/smartcontractkit/documentation/pull/909
- Add release notes for 1.8.0
=> Chainlink Node Release 1.8.0

docs/chainlink-keepers/introduction.md, docs/chainlink-keepers/job-scheduler.md, docs/chainlink-keepers/register-upkeep.md, docs/chainlink-keepers/util-overview.md, docs/getting-started/other-tutorials.md
- adds video to Job Scheduler page
- adds GIF to Register Upkeep page
- add links to external sources
- add videos for Keepers tutorials
=> Keepers Automation Blog Docs Update

_data/navigation.js, docs/chainlink-nodes/run-an-ethereum-client.md, docs/chainlink-nodes/running-a-chainlink-node.md
- Add updates to point to consensus client guides
- Remove `--syncmode fast` which is now deprecated. `snap` is the new default.
- Move Running an Ethereum Node under the Chainlink node page in the nav.
=> Update the Ethereum client guide

docs/getting-started/consuming-data-feeds.md
closes #1010 
Typo fix in "What's next" section
https://documentation-git-fork-thedriftofwords-patch-1-chainlinklabs.vercel.app/docs/consuming-data-feeds/
Fixes this typo ("Chaink Automation"):
=> Typo fix in "what's next" section

_includes/feed.liquid, _includes/por-feed.liquid
Improve the anchor handling for the data feeds lists and add a TOC to make it easier to find testnets
=> Add network TOC and improve URL anchor handling

_data/navigation.js, docs/chainlink-nodes/oracle-jobs/task-types/task_eth_call.md, docs/chainlink-nodes/oracle-jobs/task-types/task_length.md, docs/chainlink-nodes/oracle-jobs/task-types/task_lessthan.md
Not any issue, adding docs for new tasks added in https://github.com/smartcontractkit/chainlink/pull/7423/files
...
Adding documentation for new tasks added in https://github.com/smartcontractkit/chainlink/pull/7423/files
...
add docs for two new tasks
=> add docs for length and less than task

docs/data-feeds/index.md
Link to Data Feed Contract Addresses page pointing to  (/docs/data-feeds/price-feeds/) instead of  (/docs/data-feeds/price-feeds/addresses/)
...
- Changed incorrect hyperlink to Data Feed Contract Addresses page to (/docs/data-feeds/price-feeds/addresses)
=> Fixe wrong link in index.md

_data/navigation.js, docs/chainlink-nodes/node-versions.md, docs/chainlink-nodes/oracle-jobs/task-types/task_eth_call.md, docs/chainlink-nodes/oracle-jobs/task-types/task_length.md, docs/chainlink-nodes/oracle-jobs/task-types/task_lessthan.md
- Update Release Notes
- Added `length` and `lessthan` tasks
- Update `gasUnlimited` parameter for the `ethcall` task
=> CL Node release v1.9.0

docs/chainlink-nodes/miscellaneous.md, docs/chainlink-nodes/node-versions.md
Fix minor typos in RBAC md ("adamin" in command, incorrect column)
=> Fix typos in RBAC documentation

src/pages/blockchain-integrations-framework/index.md
closes #1071 
This PR offers instructions about how to resolve issues with wasmvm, a shared library that is imported by BIF.
This PR adds a quick blurb about how some operating systems and architectures require users to download [wasmvm](https://github.com/CosmWasm/wasmvm#builds-of-libwasmvm), a BIF import, and add it to their lib folder.
These instructions are required for any operating systems and architectures that use the wasmvm shared library. Otherwise, the binary will throw an error.
=> Add instructions to BIF docs for wasmvm

src/pages/chainlink-nodes/configuration-variables.md
We really don't want anyone setting this config by accident. This adds stronger language to dissuade its use.
=> Add stronger language around CHAINLINK_DEV config

public/samples/APIRequests/APIConsumer.sol, public/samples/APIRequests/ATestnetConsumer.sol, public/samples/APIRequests/FetchFromArray.sol, public/samples/APIRequests/GenericBigWord.sol, public/samples/APIRequests/GetGasPrice.sol, public/samples/APIRequests/MultiWordConsumer.sol
There was an issue during docs migration: Rinkeby samples are being used in ANY API while they are obsolete
=> any-api: put back goerli samples

.github/workflows/test.yml, src/pages/resources/link-token-contracts.md
The current URL for Polygon Bridge on the documentation redirects to a 404 page.
=> Updated the Polygon Bridge URL

src/pages/chainlink-nodes/v1/running-a-chainlink-node.md
closes #1107
...
1. I've changed ROOT path in `.env` file from `/chainlink` to `/home/chainlink`
2. I've added `--add-host=host.docker.internal:host-gateway` flag when starting Chainlink Docker container in order to reach postgres container.
- it's possible now to start Chainlink 1.11.0 node with Docker 20.04+
=> Create running-a-chainlink-node.md fixes (2022)

src/pages/getting-started/consuming-data-feeds.md, src/pages/vrf/v2/security.md
closes #1110
...
Fixes two callout issues.
Previews:
- https://documentation-git-fork-thedriftofwords-main-chainlinklabs.vercel.app/getting-started/consuming-data-feeds#compile-deploy-and-run-the-contract
- https://documentation-git-fork-thedriftofwords-main-chainlinklabs.vercel.app/vrf/v2/security
- Deletes the unnecessary self-linking callout at the top of the [VRF Security Considerations](https://docs.chain.link/vrf/v2/security/) page.
- Sets a title for a callout in [Consuming Data Feeds](https://docs.chain.link/getting-started/consuming-data-feeds#compile-deploy-and-run-the-contract).
=> Fixes two callout issues

.eleventy/_tools/networks.ts, .eleventy/docs/resources/link-token-contracts.md, scripts/networks.ts, src/features/feeds/data/chains.ts, src/pages/resources/link-token-contracts.md
Update ethstats links: ethstats.net --> ethstats.dev
...
ethstats.dev is the new link for ethstats.
See:
- https://geth.ethereum.org/docs/monitoring/ethstats#ethstats
- [internet archive results for ethstats.net](https://web.archive.org/web/20220601000000*/ethstats.net) stopping in mid-November 2022
=> Update ethstats links

public/samples/VRF/VRFD20.sol, public/samples/VRF/VRFv2Consumer.sol, public/samples/VRF/VRFv2DirectFundingConsumer.sol, public/samples/VRF/VRFv2MultiplePaths.sol, public/samples/VRF/VRFv2SubscriptionManager.sol, src/pages/vrf/v2/direct-funding/examples/get-a-random-number.md
- Update VRF's docs sample contracts from Goerli to Sepolia
- Add clarification in [Direct funding tutorial](https://docs.chain.link/vrf/v2/direct-funding/examples/get-a-random-number/) on how to set the gas limit in MetaMask; their docs and UI changed within the last 2 days.
The recent updates from Goerli to Sepolia had not included the VRF code sample contracts, so this is the follow-up update.
The MetaMask gas limit clarifications, plus info that the latest MetaMask docs didn't include:
=> Update VRF sample contracts to Sepolia; add MetaMask clarification on gas limit

src/pages/chainlink-nodes/v1/running-a-chainlink-node.mdx
closes #1278 
...
Updating the Running a Chainlink Node documentation to specify the correct two options for server and node config parameters. 
...
- Updated the step 4 bullet point, and the relevant code fragments
=> bug/2225: Running a Chainlink Node: clarifying the options for order of parameters in v2 nodes

src/pages/vrf/v2/direct-funding/supported-networks.mdx, src/pages/vrf/v2/estimating-costs.mdx
* Combine Arb estimate formula with VRF costs
* Add extended explanation of formulas and direct funding section
* Add new wrapper addresses for direct funding 
* Add [modified version](https://github.com/thedriftofwords/arbitrum-tutorials/tree/master/packages/gas-estimation) of [Arbitrum's gas estimation code sample](https://github.com/OffchainLabs/arbitrum-tutorials/tree/master/packages/gas-estimation)
TODO: For sample, switch out link to personal fork to [this repo](https://github.com/smartcontractkit/smart-contract-examples)
=> Update VRF / Arbitrum cost estimation docs

src/pages/chainlink-automation/automation-economics.mdx, src/pages/chainlink-automation/automation-release-notes.mdx, src/pages/chainlink-automation/compatible-contract-best-practice.mdx, src/pages/chainlink-automation/compatible-contracts.mdx, src/pages/chainlink-automation/faqs.mdx, src/pages/chainlink-automation/flexible-upkeeps.mdx, src/pages/chainlink-automation/introduction.mdx, src/pages/chainlink-automation/job-scheduler.mdx, src/pages/chainlink-automation/manage-upkeeps.mdx, src/pages/chainlink-automation/overview.mdx, src/pages/chainlink-automation/register-upkeep.mdx, src/pages/chainlink-automation/supported-networks.mdx, src/pages/chainlink-automation/tutorials/batch-nft.mdx, src/pages/chainlink-automation/tutorials/counting-dnft.mdx, src/pages/chainlink-automation/tutorials/dynamic-nft.mdx, src/pages/chainlink-automation/tutorials/eth-balance.mdx, src/pages/chainlink-automation/tutorials/vault-harvester.mdx, src/pages/chainlink-automation/tutorials/vrf-sub-monitor.mdx, src/pages/chainlink-automation/util-overview.mdx
* Spacing fixes
* Remove `isMdx` and trailing slashes in "What's next" links (missed in #1289 )
* Misc edits
=> Minor misc fixes to Automation docs

.github/workflows/chains-metadata.yml
`set-output` is deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Update GH workflow

src/pages/getting-started/intermediates-tutorial.mdx
Updates incorrect hardcoded variables for the coordinator address and keyhash in the [VRF intro tutorial](https://docs.chain.link/getting-started/intermediates-tutorial#contract-variables). 
Follow-up to #1125 and #1163.
=> Update hardcoded Goerli variables to Sepolia in VRF intro tutorial

src/pages/chainlink-automation/compatible-contracts.mdx
In the link https://docs.chain.link/chainlink-automation/compatible-contracts#example-contract, step 3 of the tutorial says to copy the deployed contract address to be able to register the user's upkeep. However, there's no next steps afterwards. The next step is to actually go to the page https://docs.chain.link/chainlink-automation/register-upkeep but there's no mention of it. 
...
At step 3 of the getting started tutorial for chainlink-automation, Link added to navigate to the appropriate page so that the user will be able to register its upkeep and see an example of how chainlink automation works.
=> Add link to custom logic automation guide in getting started page

src/components/CopyText.tsx, src/pages/ccip/getting-started.mdx, src/pages/ccip/tutorials/cross-chain-tokens.mdx, src/pages/ccip/tutorials/programmable-token-transfers.mdx, src/pages/ccip/tutorials/send-arbitrary-data.mdx
https://github.com/smartcontractkit/documentation/issues/1407
My CCIP token transfer expected to revert since the LINK fee increased. 
Helps new users debug the CCIP transfer revert issue due to LINK fee increasing by giving them a warning.
=> CCIP token transfer tutorial revert error fix add more LINK for fee

src/pages/ccip/architecture.mdx
Fix typo, fix bullet points and add non-breaking spaces where needed in CCIP Architecture and Billing
- Fixing a typo. Contact -> Contract
- Fixing bullet points. Added a missing line break to add a missing bullet point
- Adding spaces. MDX doesn't preserve white space after italics in quotes, using non-breaking spaces where needed
=> Fix typo, fix bullet points and add non-breaking spaces where needed in CCIP Architecture and Billing in architecture.mdx

src/pages/ccip/best-practices.mdx
Follow-up of the previous PR about EOA address typo to change it to EOA in CCIP page.
Applied the same fix to Best Practices tab in https://docs.chain.link/ccip/best-practices#setting-gaslimit
=> Fix typo EOA address by EOA in CCIP page

src/content/vrf/v2/subscription/index.mdx
closes #1514 
There is a repetition of 'implement the' in the vrf subscription introduction page here https://docs.chain.link/vrf/v2/subscription/#set-up-your-contract-and-request in the second step.
Removed the repetition.
=> Fix typo in vrf subscription introduction page

src/content/quickstarts/vrf-enabled-lootbox-pack.mdx
The command npx hardhat run scripts/deploy.js --network <network> does not work because the script is called deploy.ts. 
Fix the issue by replacing deploy.js mention by deploy.ts instead.
=> Fix typo in script name in lootbox quickstart

src/features/landing/components/ProductCard.module.css, src/features/landing/components/Tabs.module.css, src/features/landing/sections/HeroCTA.astro
Closes [FRONT-4421](https://smartcontract-it.atlassian.net/browse/FRONT-4421)
The `ProductCard` components were using a fixed width with flex wrap to break across lines, but this created overflow on smaller displays. This fixes the overflow by aligning them to a grid in `Tabs`. This also adds a top margin to `HeroCTA`, which is required on mobile to not be awkwardly close to the top of the page.
- Aligns `ProductCard` components to grid in `Tabs`
- Adds margin to `HeroCTA`
=> Fix homepage sizing

CONTRIBUTING.md, src/content/chainlink-nodes/v1/secrets-config.mdx
AllowSimplePasswords is now disallowed for secure builds. Updating secrets config documentation accordingly.
=> fix/AllowSimplePasswords: true disallowed for secure builds

src/content/any-api/get-request/examples/large-responses.mdx, src/content/chainlink-nodes/v1/configuration.mdx
Update URL placeholder notation to allcaps. Update pipe character notation to add breaks and allow translation.
=> Update notation for URL and pipe chars

src/content/chainlink-functions/getting-started.mdx
Bullet no. 3 in https://docs.chain.link/chainlink-functions/getting-started?lang=en#run-the-example, the image encroaches the line of text. Adding break to prevent.
=> Add line break to avoid image encroachment

src/components/LeftSidebar/LeftSidebar.astro
`LeftSidebar` section entries were appearing misaligned. This was due to the svg elements (hex logo) on selected sections being resized if the section text spanned multiple lines. This change adds `min-width` and `min-height` properties to prevent the svgs from resizing.
=> Fix LeftSidebar sections from appearing misaligned

src/content/ccip/tutorials/cross-chain-tokens.mdx
Replaces incorrect function name from `transferTokensPayNative` to `transferTokensPayLINK`
None
There was a typo under the `Explanation` header for `transferTokensPayLINK`. 
[Reference](https://docs.chain.link/ccip/tutorials/cross-chain-tokens#transferring-tokens-and-pay-in-link)
The tokenAmounts is an array, with each element comprising a [EVMTokenAmount struct](https://docs.chain.link/ccip/api-reference/client#evmtokenamount) that contains the token address and amount. The array contains one element where the _token (token address) and _amount (token amount) are passed by the user when calling the **transferTokensPayNative** function.
Instead of `transferTokensPayLINK` the mention was that of `transferTokensPayNative`.
This PR fixes the above mentioned typo and makes the documentation …
=> fixes typo: replaces incorrect function name

src/components/LeftSidebar/LeftSidebar.astro
Fixes the width of the sidebar so that the caret doesn't jump left and right.
=> Fix Sidebar caret jumping around

src/content/chainlink-automation/overview/getting-started.mdx
https://documentation-git-fork-thedriftofwords-add-9b6c6c-chainlinklabs.vercel.app/chainlink-automation/overview/getting-started
=> Correct old addresses and minor edits in Automation Getting Started

public/samples/Automation/StreamsWithError.sol, src/content/chainlink-automation/guides/streams-lookup-error-handler.mdx
https://documentation-git-fork-thedriftofwords-cla-fix-chainlinklabs.vercel.app/chainlink-automation/guides/streams-lookup-error-handler
=> Fix an error code

src/content/chainlink-automation/concepts/best-practice.mdx
https://documentation-git-thedriftofwords-cla-best-fa0841-chainlinklabs.vercel.app/chainlink-automation/concepts/best-practice#automation-v1-upkeep-revalidation
=> Add V1 revalidation to best practices

public/samples/ChainlinkFunctions/GettingStartedFunctionsConsumer.sol, public/samples/ChainlinkFunctions/starwars-api.js, src/content/chainlink-functions/getting-started.mdx
- swapi.dev: not available anymore
- swapi.info: to align with the API endpoints used in the playground
=> External Links Quick Fixes (404 Errors)

public/samples/ChainlinkNodes/forwarder/get-string.toml, public/samples/ChainlinkNodes/forwarder/get-uint256.toml, public/samples/ChainlinkNodes/jobs/get-bytes32.toml, public/samples/ChainlinkNodes/jobs/get-string.toml, public/samples/ChainlinkNodes/jobs/get-uint256.toml
Job is not working without evmChainID in Sepolia Tesnet. I added it to get-uint256.toml file.
...
...
- High level
- changes that
- you made
- ...
=> Update get-uint256.toml evmChainID

src/content/vrf/release-notes.mdx, src/content/vrf/v2/subscription/supported-networks.mdx
https://documentation-git-fork-thedriftofwords-vrf-fantom-chainlinklabs.vercel.app/vrf/release-notes#2024-03-29---fantom-support-changed
https://documentation-git-fork-thedriftofwords-vrf-fantom-chainlinklabs.vercel.app/vrf/v2/subscription/supported-networks#fantom-mainnet
=> VRF Fantom support change

src/content/chainlink-automation/concepts/best-practice.mdx
https://documentation-git-fork-thedriftofwords-aut-4f48c2-chainlinklabs.vercel.app/chainlink-automation/concepts/best-practice#avoid-flickering-custom-logic-upkeeps
=> Clarify flickering upkeeps

src/content/ccip/tutorials/send-arbitrary-data.mdx
Fixes an issue in this section - https://docs.chain.link/ccip/tutorials/send-arbitrary-data#send-data-and-pay-in-native
Has the Fuji chain selector:
=> Update a chain selector

src/content/ccip/tutorials/cross-chain-tokens.mdx
Clarifying a sentence regarding accessing smart contract functions on Avalanche Fuji. The phrase "open the list of your smart contract deployed on Avalanche Fuji" is changed to "open the list of functions for your smart contract deployed on Avalanche Fuji." This change aims to provide clearer instructions to users about the specific information they can access related to their deployed smart contracts on Avalanche Fuji.
The opened issue:  #1891
=> Clarify smart contract function listing

src/content/ccip/tutorials/get-status-offchain.mdx
This pull request updates the source chain name in the transaction status check command usage statement from "Ethereum Sepolia testnet" to "Avalanche Fuji testnet".
=> Update Source Chain Name

src/config/data/chains.json, src/content/resources/link-token-contracts.mdx, src/features/data/chains.ts, src/scripts/reference/chains.json
=> Add new Amoy block explorer URL

src/content/chainlink-functions/resources/release-notes.mdx, src/content/chainlink-functions/supported-networks.mdx
https://documentation-git-fork-thedriftofwords-cf-amoy-chainlinklabs.vercel.app/chainlink-functions/supported-networks#polygon-amoy-testnet
https://documentation-git-fork-thedriftofwords-cf-amoy-chainlinklabs.vercel.app/chainlink-functions/resources/release-notes
=> CF: Add Polygon Amoy

src/features/chainlink-automation/data/chainlink-automation-config.json
Update CLA supported networks page to reflect 10M checkGasLimit across all networks (for v2.1)
https://documentation-git-thedriftofwords-cla-correction-chainlinklabs.vercel.app/chainlink-automation/overview/supported-networks
=> Correcting checkGasLimit to 10M

src/content/chainlink-automation/overview/automation-release-notes.mdx
https://documentation-git-fork-thedriftofwords-cla-c29f5d-chainlinklabs.vercel.app/chainlink-automation/overview/automation-release-notes#2024-06-03---registrar-deprecation-through-v20
=> Add note on old registrar deprecations

src/content/chainlink-nodes/resources/requirements.mdx
The `Blockchain Connectivity` section  on our docs has a `supported clients` links that points to a `v1.13beta` branch. Fixing it to link to the current version.
=> Update supported clients link to stable version

src/config/sidebar.ts, src/content/vrf/v2-5/migration-from-v1.mdx
https://documentation-git-fork-thedriftofwords-vrf-a6feb1-chainlinklabs.vercel.app/vrf/v2-5/migration-from-v1
=> VRF: Migration from V1 guide

src/content/chainlink-functions/resources/billing.mdx, src/content/chainlink-functions/resources/release-notes.mdx, src/content/chainlink-functions/supported-networks.mdx
https://documentation-git-fork-thedriftofwords-073-0278bd-chainlinklabs.vercel.app/chainlink-functions/supported-networks - ETH, Sepolia, Arbitrum and Avalanche mainnets
Also updated
- [Release notes](https://documentation-git-fork-thedriftofwords-073-0278bd-chainlinklabs.vercel.app/chainlink-functions/resources/release-notes#usd-denominated-premium-fees-on-all-networks---2024-07-31)
- [Cost calculation example](https://documentation-git-fork-thedriftofwords-073-0278bd-chainlinklabs.vercel.app/chainlink-functions/resources/billing#cost-calculation-example) has had the tabs with the LINK-denominated premium examples removed
=> Functions: all networks use USD-denominated premium fees

src/features/chainlink-automation/data/chainlink-automation-config.json
Fix blank "max perform data size" for BNB testnet in docs
preview: https://documentation-git-08202024-cla-fix-chainlinklabs.vercel.app/chainlink-automation/overview/supported-networks#bnb-chain-testnet
=> CLA supported networks bugfix

src/content/vrf/v2-5/migration-from-v2.mdx
https://documentation-git-docs-vrf-notice-updates-chainlinklabs.vercel.app/vrf/v2-5/migration-from-v2
=> Add VRF v2.5 notice to V2 migration page

src/components/DocsNavigation/DocsNavigationDesktop/docsNavigationDesktop.module.css, src/components/DocsNavigation/DocsNavigationMobile/docsNavigationMobile.module.css, src/components/Header/Nav/NavBar.tsx, src/components/Header/Nav/navBar.module.css, src/components/Header/NavBar.tsx, src/layouts/QuickstartLayout.astro
- Add border at the bottom of navigation
- Ensure Shadow is shown in inner pages (Eg. quickStarts)
=> Fix shadow on navigation

public/samples/VRF/v2-5/SubscriptionConsumer.sol
closes #2136 
...
Updates the file with the correct link
...
Comments for Supported Networks went to a 404 Page not found
Previous link goes to a 404 Page not found:
https://docs.chain.link/docs/vrf/v2-5/supported-networks 
Updated to the correct page:
https://docs.chain.link/vrf/v2-5/supported-networks
=> Updates docs link for SubscriptionConsumer.sol

src/features/redirects/redirects.json
To test try
https://documentation-git-fork-thedriftofwords-redirects-chainlinklabs.vercel.app/ccip/supported-networks/v1_2_0/mainnet#arbitrum-mainnet
=> Add redirects for old CCIP v1.2 supported networks urls

src/content/data-feeds/index.mdx, src/content/data-feeds/rates-feeds/index.mdx
- "Chailink's" -> "Chainlink's"
Reason: Fixed company name typo
- Removed redundant "the" before "real-world data"
- Removed duplicate word "feeds" in "L2 sequencer uptime feeds feeds"
- Verified links functionality
- Confirmed proper formatting
- Checked terminology consistency
=>  Documentation Updates

src/config/sidebar/ccip/api-reference/v1_5_0.json, src/config/sidebar/ccip/api-reference/v1_5_1.json, src/config/versions/page-availability.ts, src/content/ccip/api-reference/v1.5.0/i-type-and-version.mdx, src/content/ccip/api-reference/v1.5.1/burn-from-mint-token-pool.mdx, src/content/ccip/api-reference/v1.5.1/burn-mint-erc20.mdx, src/content/ccip/api-reference/v1.5.1/burn-mint-token-pool-abstract.mdx, src/content/ccip/api-reference/v1.5.1/burn-mint-token-pool.mdx, src/content/ccip/api-reference/v1.5.1/ccip-receiver.mdx, src/content/ccip/api-reference/v1.5.1/client.mdx, src/content/ccip/api-reference/v1.5.1/i-router-client.mdx, src/content/ccip/api-reference/v1.5.1/i-type-and-version.mdx, src/content/ccip/api-reference/v1.5.1/index.mdx, src/content/ccip/api-reference/v1.5.1/lock-release-token-pool.mdx, src/content/ccip/api-reference/v1.5.1/ownable-2-step-msg-sender.mdx, src/content/ccip/api-reference/v1.5.1/ownable-2-step.mdx, src/content/ccip/api-reference/v1.5.1/pool.mdx, src/content/ccip/api-reference/v1.5.1/rate-limiter.mdx, src/content/ccip/api-reference/v1.5.1/registry-module-owner-custom.mdx, src/content/ccip/api-reference/v1.5.1/token-admin-registry.mdx, src/content/ccip/api-reference/v1.5.1/token-pool.mdx, src/content/ccip/best-practices.mdx
This pull request includes several updates to the Chainlink CCIP API documentation and configuration files. The most important changes include adding new API references, updating page availability configurations, and enhancing documentation for specific interfaces and contracts.
* Added `ITypeAndVersion` to the API references for versions 1.5.0 and 1.5.1 in the `sidebar` configuration files. [[1]](diffhunk://#diff-be409746c58d7a1a2e4f710a1adac670ee8b059dea1f5b949b7e334ff5361b69R6-R9) [[2]](diffhunk://#diff-67cb7464fa4b4df952f733ece141b9a025b2dff79015682f76987fcfcbd4c8f4R6-R9)
* Added `Ownable2Step` and `Ownable2StepMsgSender` to the API reference for version 1.5.1 in the `sidebar` configuration file.
* Updated `page-availability.ts` to include `ownable-2-step` and …
=> fix ccip v1.5.1 api ref

src/features/utils/index.ts
This pull request includes a new utility function to transform token names and updates the `getTokenIconUrl` function to use this transformation. The most important changes include the addition of the `transformTokenName` function and the modification of the `getTokenIconUrl` function to utilize this new transformation.
* [`src/features/utils/index.ts`](diffhunk://#diff-ab32fa9ac696824a2301b0bea9c3f544bb8ebb477310da7ebcc5607a04b7fac3R66-R86): Added the `transformTokenName` function to convert token names to lowercase, remove dots, and replace plus signs with `%2B`.
* [`src/features/utils/index.ts`](diffhunk://#diff-ab32fa9ac696824a2301b0bea9c3f544bb8ebb477310da7ebcc5607a04b7fac3R66-R86): Updated the `getTokenIconUrl` function to use the `transformTokenName` function for transforming token …
=> change get token url

src/content/quickstarts/automated-portfolio-manager.mdx
Linked PR: https://github.com/smartcontractkit/quickstarts-automated-portfolio-manager/pull/2
=> Automated Portfolio QS maintenance

src/features/feeds/components/FeedList.tsx
This pull request includes updates to the `FeedList` component in `src/features/feeds/components/FeedList.tsx` to enhance the handling of different data feed types, specifically for "streamsCrypto" and "streamsRwa". The most important changes include the introduction of a new state variable for streams, adjustments to the network selection logic, and the reorganization of the `isStreams` variable.
Enhancements to data feed type handling:
* Introduced a new constant `isStreams` to determine if the `dataFeedType` is "streamsCrypto" or "streamsRwa", and adjusted the initial value of `selectedChain` based on this condition.
* Added a new state variable `streamsChain` for handling the initial network when `dataFeedType` is a stream, and updated the `activeChain` and `chain` variables …
=> Remove network name from URL params

src/features/feeds/components/Tables.tsx
This pull request includes changes to the `src/features/feeds/components/Tables.tsx` file to simplify the code by removing redundant `docs` references and directly accessing properties from the `proxy` and `chain` objects. 
The most important changes include:
Code simplification:
* [`src/features/feeds/components/Tables.tsx`](diffhunk://#diff-ef3526edcbc07ee07216ef3f69138a4fcf75429e5783f0a1ce8f4fb960c82904L142-R142): Modified the `DefaultTr` component to access `feedCategory`, `assetName`, and `feedType` directly from the `proxy` object instead of through `proxy.docs`. [[1]](diffhunk://#diff-ef3526edcbc07ee07216ef3f69138a4fcf75429e5783f0a1ce8f4fb960c82904L142-R142) [[2]](diffhunk://#diff-ef3526edcbc07ee07216ef3f69138a4fcf75429e5783f0a1ce8f4fb960c82904L185-R199)
* …
=> Refactor: move some feed metadata from docs to root level

src/content/data-feeds/l2-sequencer-feeds.mdx
I found a broken link in the documentation. In the official Discord, I was advised to replace it with this: [https://docs.optimism.io/stack/rollup/overview]. If you have any other suggestions or disagree with this change, please share your version, and I will update it accordingly.
=> Fix broken link

src/config/data/ccip/v1_2_0/mainnet/lanes.json, src/config/data/ccip/v1_2_0/mainnet/tokens.json
This pull request includes several changes to the `src/config/data/ccip/v1_2_0/mainnet/lanes.json` and `src/config/data/ccip/v1_2_0/mainnet/tokens.json` files. The changes primarily involve the addition of a new token configuration for "SAS" and modifications to the rate limiter configurations for existing tokens.
* Added configuration for the "SAS" token in various networks, including `bsc-mainnet`, `mainnet`, and `shibarium-mainnet`.
* Reduced the `capacity` and `rate` for `SolvBTC` and `SolvBTC.BBN` from `15000000000000000000` to `2500000000000000000` and from `694400000000000` to `115740000000000` respectively in multiple instances. [[1]](diffhunk://#diff-b164fc5a30b147936f54f068274980bfd2dcbe919ced745997633103fbfb8844L6182-R6168) …
=> CCIP: SAS token

src/content/chainlink-functions/tutorials/simple-computation.mdx, src/features/chainlink-functions/common/DenoImportNotes.mdx
Removed the warning that imports are only available on Testnet.
=> FIX: Imports for Functions are available on Mainnet

src/features/feeds/components/FeedList.tsx
This pull request introduces significant improvements to the `FeedList` component, primarily focusing on enhancing the scroll restoration logic, dynamically updating section IDs, and ensuring the Table of Contents (TOC) reflects these updates. Additionally, changes were made to streamline the handling of section IDs in the `SectionWrapper` component.
* Enhanced the scroll restoration logic to dynamically update section IDs based on network data, ensuring proper alignment with URL hashes. This includes handling testnet sections and updating anchor links within headings.
* Added functionality to update the Table of Contents (TOC) links whenever section IDs are modified, ensuring accurate navigation. This includes triggering a TOC update via the `updateTableOfContents` function.
* Introduced …
=> Fix: anchor navigation by updating section IDs, heading links and TOC

src/features/notifications/data/index.ts
Chainlink CCIP is now officially live on Solana. [View lanes and tokens](https://docs.chain.link/ccip/directory/mainnet/chain/solana-mainnet?utm_medium=referral&utm_source=chainlink-docs&utm_campaign=solana-ccip).
=> add new banner for ccip solana

src/components/QuickLinks/data/productChainLinks.ts, src/content/chainlink-automation/overview/supported-networks.mdx
remove fantom from supported networks and quick links for automation
=> Fantom removal from Automation

src/config/data/ccip/v1_2_0/mainnet/lanes.json, src/config/data/ccip/v1_2_0/mainnet/tokens.json, src/config/data/ccip/v1_2_0/testnet/chains.json, src/config/data/ccip/v1_2_0/testnet/lanes.json, src/config/data/ccip/v1_2_0/testnet/tokens.json
This pull request makes significant updates to the rate limiter configurations for supported tokens within the `src/config/data/ccip/v1_2_0/mainnet/lanes.json` file. The main changes include adding new tokens with disabled rate limiters, adjusting the rate limiter settings for existing tokens (notably `uniBTC` and several others), and removing the `wstLINK` token from multiple lane configurations.
**Token additions and removals:**
* Added new tokens (`TREE`, `beraBTC`, `WLFI`, `YNE`) to various lanes, each with rate limiter configurations set to disabled (capacity and rate set to zero, isEnabled: false). [[1]](diffhunk://#diff-b164fc5a30b147936f54f068274980bfd2dcbe919ced745997633103fbfb8844R1043-R1056) [[2]](diffhunk://#diff-b164fc5a30b147936f54f068274980bfd2dcbe919ced745997633103fbfb8844R …
=> refresh directory

public/changelog.json, src/components/QuickLinks/data/productChainLinks.ts
...
...
- High level
- changes that
- you made
- ...
=> Add Aptos to changelog and quicklinks

src/features/notifications/data/index.ts
This pull request updates the notification banner content to announce a new product launch and provide a relevant link.
- **Notification Banner Update:**
* Changed the `description` in `NotificationData` to announce the launch of DataLink with Deutsche Börse, replacing the previous CCIP announcement.
* Updated the `linkText` to "Learn more." and the `linkUrl` to point to the DataLink launch blog post instead of the CCIP documentation.
=> add new datalink announcement
